import {useState} from 'react';
import {api} from './api';
type Report={scope:string;from_date:string;to_date:string;timezone:string;generated_at:string;total:number;unknown_dates:number;company_groups:number;statuses:any[];stages:any[];activity:any[];companies:any[];sources:any[];outcomes:any[];observed_funnel:any[]};
export function AnalyticsWorkspace({locale,staff}:{locale:'en'|'ms';staff:boolean}){
 const ms=locale==='ms',t=(en:string,bm:string)=>ms?bm:en;
 const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kuala_Lumpur'});
 const [scope,setScope]=useState('candidate'),[from,setFrom]=useState(''),[to,setTo]=useState(today),[zone,setZone]=useState('Asia/Kuala_Lumpur'),[company,setCompany]=useState(''),[origin,setOrigin]=useState('all'),[source,setSource]=useState(''),[job,setJob]=useState(''),[archive,setArchive]=useState(false);
 const [data,setData]=useState<Report|null>(null),[exportQuery,setExportQuery]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){setBusy(true);setMessage('');setData(null);setExportQuery('');try{const query=new URLSearchParams({scope,timezone:zone,company,source,origin:scope==='staff'?'internal':origin,archived:String(archive),...(from?{from_date:from}:{}),...(to?{to_date:to}:{}),...(scope==='staff'&&job?{job_id:job}:{})});const r=await api<Report>('/analytics/report?'+query);query.set('from_date',r.from_date);query.set('to_date',r.to_date);setData(r);setExportQuery(query.toString());}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 function bars(title:string,rows:any[],key:string){const max=Math.max(1,...rows.map(r=>r.count??r.applications??0));return <table tabIndex={0} aria-label={title}><caption>{title}</caption><thead><tr><th scope="col">{t('Origin','Asal')}</th><th scope="col">{t('Category','Kategori')}</th><th scope="col">{t('Applications','Permohonan')}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.origin||'internal'}</td><th scope="row">{r[key]}</th><td>{r.count??r.applications??0}<span aria-hidden="true" style={{display:'block',height:8,background:'var(--desktop-accent, #245ca6)',width:((r.count??r.applications??0)/max*100)+'%'}}/></td></tr>)}{rows.length===0&&<tr><td colSpan={3}>{t('No data in this cohort','Tiada data dalam kohort ini')}</td></tr>}</tbody></table>;}
 return <section className="panel" aria-label={t('Analytics workspace','Ruang analitik')}><h2>{t('Application analytics','Analitik permohonan')}</h2><p>{t('Descriptive counts, not acceptance predictions. Internal outcomes are confirmed by KerjaOS; manual/discovery activity is self-reported. Saved/considering roles are tracked records, not submitted applications.','Kiraan deskriptif, bukan ramalan penerimaan. Hasil dalaman disahkan KerjaOS; aktiviti manual/penemuan dilaporkan sendiri. Jawatan disimpan/dipertimbangkan ialah rekod penjejak, bukan permohonan dihantar.')}</p>
 <form onSubmit={e=>{e.preventDefault();void load();}}>
 <label>{t('Report scope','Skop laporan')}<select aria-label="Analytics scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="candidate">{t('My activity','Aktiviti saya')}</option>{staff&&<option value="staff">{t('Assigned jobs · staff MFA','Jawatan ditugaskan · MFA staf')}</option>}</select></label>
 <label>{t('From (blank: last 90 days)','Dari (kosong: 90 hari lepas)')}<input aria-label="Analytics from" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{t('Until','Sehingga')}<input aria-label="Analytics until" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>
 <label>{t('IANA timezone','Zon waktu IANA')}<input aria-label="Analytics timezone" required maxLength={80} value={zone} onChange={e=>setZone(e.target.value)}/></label><label>{t('Company contains','Syarikat mengandungi')}<input aria-label="Analytics company" maxLength={120} value={company} onChange={e=>setCompany(e.target.value)}/></label>
 <label>{t('Source contains','Sumber mengandungi')}<input aria-label="Analytics source" maxLength={120} value={source} onChange={e=>setSource(e.target.value)}/></label>
 {scope==='candidate'?<><label>{t('Origin','Asal')}<select aria-label="Analytics origin" value={origin} onChange={e=>setOrigin(e.target.value)}>{['all','internal','manual','discovery'].map(v=><option key={v}>{v}</option>)}</select></label><label><input type="checkbox" checked={archive} onChange={e=>setArchive(e.target.checked)}/>{t('Include archived external records','Sertakan rekod luaran diarkib')}</label></>:<label>{t('Assigned job UUID (blank: all assigned)','UUID jawatan ditugaskan (kosong: semua)')}<input aria-label="Analytics job" value={job} onChange={e=>setJob(e.target.value)}/></label>}
 <button disabled={busy}>{t('Load analytics','Muat analitik')}</button></form><p role="status">{message}</p>
 {data&&<><p>{data.scope} · {data.from_date} → {data.to_date} · {data.timezone} · {data.generated_at}</p><p>{t('Cohort records','Rekod kohort')}: <strong>{data.total}</strong> · {t('Unknown applied dates excluded','Tarikh mohon tidak diketahui dikecualikan')}: <strong>{data.unknown_dates}</strong></p><p>{t('Internal cohort date is creation in the selected timezone; manual date is explicitly entered. Discovery dates remain unknown. Maximum 366 days. Filters apply on refresh; exports reuse loaded filters and refresh current counts.','Tarikh kohort dalaman ialah penciptaan dalam zon waktu dipilih; tarikh manual dimasukkan sendiri. Tarikh penemuan tidak diketahui. Maksimum 366 hari. Penapis digunakan semasa muat semula; eksport menggunakan penapis dimuat dan menyegarkan kiraan semasa.')}</p>
 <a href={'/api/v1/analytics/export?'+exportQuery+'&format=csv'}>{t('Export analytics CSV','Eksport analitik CSV')}</a> · <a href={'/api/v1/analytics/export?'+exportQuery+'&format=json'}>{t('Export analytics JSON','Eksport analitik JSON')}</a>
 <table tabIndex={0} aria-label={t('Current outcomes','Hasil semasa')}><caption>{t('Current outcomes · denominator is each origin cohort','Hasil semasa · penyebut ialah kohort setiap asal')}</caption><thead><tr>{[t('Origin','Asal'),t('Records','Rekod'),t('Interviews','Temu duga'),t('Offers incl. accepted/hired','Tawaran termasuk diterima/diambil'),t('Hires','Pengambilan'),t('Rejections','Penolakan'),t('Withdrawals','Penarikan'),t('Closures','Penutupan')].map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{data.outcomes.map(r=><tr key={r.origin}>{['origin','denominator','interviews','offers','hires','rejections','withdrawals','closures'].map(k=><td key={k}>{r[k]}</td>)}</tr>)}</tbody></table>
 <p>{t('Internal interviews count distinct applications with a currently confirmed/completed human booking. External interviews are a current self-reported status. These are current snapshots, not lifetime conversions. Closure is separate from rejection.','Temu duga dalaman mengira permohonan berbeza dengan tempahan manusia disahkan/selesai semasa. Temu duga luaran ialah status laporan kendiri semasa. Ini snapshot semasa, bukan penukaran sepanjang masa. Penutupan berasingan daripada penolakan.')}</p>
 {bars(t('Current statuses · snapshot','Status semasa · snapshot'),data.statuses,'status')}{bars(t('Current internal stages · snapshot','Fasa dalaman semasa · snapshot'),data.stages,'stage')}
 <table tabIndex={0} aria-label={t('Current stage age','Umur fasa semasa')}><caption>{t('Current stage age · observed entries only','Umur fasa semasa · kemasukan diperhatikan sahaja')}</caption><thead><tr>{[t('Stage','Fasa'),t('Known / total','Diketahui / jumlah'),t('Mean days','Purata hari')].map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{data.stages.map(r=><tr key={r.stage}><th scope="row">{r.stage}</th><td>{r.known_age_count} / {r.count}</td><td>{r.mean_age_days??t('Unknown','Tidak diketahui')}</td></tr>)}</tbody></table>
 {bars(t('Application-date activity','Aktiviti tarikh permohonan'),data.activity,'day')}{bars(t('Companies · top 50 groups','Syarikat · 50 kumpulan teratas'),data.companies,'company')}<p>{t('Company groups omitted','Kumpulan syarikat tidak dipaparkan')}: {Math.max(0,data.company_groups-data.companies.length)}</p>{bars(t('Sources','Sumber'),data.sources,'source')}
 {bars(t('Observed stage entries · distinct applications','Kemasukan fasa diperhatikan · permohonan berbeza'),data.observed_funnel,'stage')}<p>{t('Stage observations start with M11. Older histories have unknown entry times. Each stage counts an application once in this cohort/range; re-entry and notes do not multiply counts. Denominator','Pemerhatian fasa bermula dengan M11. Sejarah lama tiada waktu kemasukan diketahui. Setiap fasa mengira satu permohonan sekali dalam kohort/julat ini; kemasukan semula dan nota tidak menggandakan kiraan. Penyebut')}: {data.outcomes.find(r=>r.origin==='internal')?.denominator??0}</p>
 </>}
 </section>;
}
