import {type CSSProperties,useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Bell,ChevronLeft,ChevronRight,Pause,Play,RotateCcw} from 'lucide-react';

export type CalendarEvent={id:string;title:string;starts_at:string;ends_at:string;kind?:string};
export type BentoTask={id:string;title:string;due:string;done:boolean};
export function dayKey(value:Date|string){return new Date(value).toLocaleDateString('en-CA',{timeZone:'Asia/Kuala_Lumpur'})}
function monday(value:Date){const d=new Date(dayKey(value)+'T12:00:00+08:00');d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return d}
function shift(value:Date,n:number){const d=new Date(value);d.setUTCDate(d.getUTCDate()+n);return d}
export function WeekCalendar({events,onEvent,onNew,locale='en'}:{events:CalendarEvent[];onEvent:(event:CalendarEvent)=>void;onNew?:(date:string)=>void;locale?:'en'|'ms'}){
 const [week,setWeek]=useState(()=>monday(new Date()));const days=Array.from({length:6},(_,i)=>shift(week,i));
 const fmt=(d:Date,options:Intl.DateTimeFormatOptions)=>d.toLocaleDateString(locale==='ms'?'ms-MY':'en-GB',{timeZone:'Asia/Kuala_Lumpur',...options});
 const [selected,setSelected]=useState(dayKey(new Date()));
 return <section className="bento-card bento-calendar" aria-label="Week calendar"><header><button aria-label="Previous week" onClick={()=>setWeek(shift(week,-7))}><ChevronLeft size={14}/><span>{fmt(shift(week,-7),{month:'short',day:'numeric'})}</span></button><h2>{fmt(week,{month:'short',day:'numeric'})} – {fmt(days[5],{month:'short',day:'numeric'})}</h2><button aria-label="Next week" onClick={()=>setWeek(shift(week,7))}><span>{fmt(shift(week,7),{month:'short',day:'numeric'})}</span><ChevronRight size={14}/></button></header>
 <div className="week-day-head"><button className="calendar-today" onClick={()=>{setWeek(monday(new Date()));setSelected(dayKey(new Date()))}}>Today</button>{days.map(d=><button key={dayKey(d)} aria-pressed={selected===dayKey(d)} onClick={()=>setSelected(dayKey(d))}>{fmt(d,{weekday:'short'})}<strong>{fmt(d,{day:'numeric'})}</strong></button>)}</div>
 <div className="week-scroll" tabIndex={0} aria-label="Calendar hours"><div className="week-grid"><div className="week-hours">{Array.from({length:10},(_,i)=><span key={i}>{i+8}:00</span>)}</div>{days.map(d=><div className={'week-column'+(selected===dayKey(d)?' selected':'')} key={dayKey(d)}>{Array.from({length:10},(_,i)=><button className="week-cell" key={i} aria-label={'Schedule '+dayKey(d)+' at '+(i+8)+':00'} disabled={!onNew} onClick={()=>onNew?.(dayKey(d)+'T'+String(i+8).padStart(2,'0')+':00:00+08:00')}/>)}{events.filter(e=>dayKey(e.starts_at)===dayKey(d)).map(e=>{const h=Number(new Date(e.starts_at).toLocaleString('en-GB',{timeZone:'Asia/Kuala_Lumpur',hour:'2-digit',hour12:false}));const m=Number(new Date(e.starts_at).toLocaleString('en-GB',{timeZone:'Asia/Kuala_Lumpur',minute:'2-digit'}));const duration=(Date.parse(e.ends_at)-Date.parse(e.starts_at))/60000;return <button key={e.id} className={'week-event '+(e.kind||'')} style={{top:Math.max(0,Math.min(370,(h-8+m/60)*42)),height:Math.max(30,Math.min(84,duration/60*42))}} onClick={()=>onEvent(e)} title={e.title}>{e.title}</button>})}</div>)}</div></div>{!events.some(e=>dayKey(e.starts_at)>=dayKey(week)&&dayKey(e.starts_at)<=dayKey(days[5]))&&<p className="calendar-empty">No scheduled events this week.</p>}
 </section>
}
export function WeeklyGraph({values,label,onOpen}:{values:number[];label:string;onOpen:()=>void}){
 const [active,setActive]=useState(6);const max=Math.max(1,...values);const total=values.reduce((a,b)=>a+b,0);
 return <section className="bento-card bento-progress"><header><h2>Progress</h2><button className="round-button" aria-label="Open progress report" onClick={onOpen}><ArrowUpRight size={18}/></button></header><div className="progress-summary"><strong>{total.toFixed(1)}</strong><span>{label}<small>last 7 days</small></span></div><div className="week-bars" aria-label={label}>{values.map((v,i)=><button key={i} className={active===i?'active':''} aria-label={'Day '+(i+1)+': '+v+' '+label} aria-pressed={active===i} onClick={()=>setActive(i)}><span className="bar-value">{v}</span><span className="bar-stem" style={{height:Math.max(4,66*v/max)}}/><i/><small>{shift(new Date(dayKey(new Date())+'T12:00:00+08:00'),i-6).toLocaleDateString('en-GB',{weekday:'narrow',timeZone:'Asia/Kuala_Lumpur'})}</small></button>)}</div></section>
}
export function SessionTimer({onSave}:{onSave?:(minutes:number)=>Promise<void>}){
 const [seconds,setSeconds]=useState(0),[running,setRunning]=useState(false),[alarm,setAlarm]=useState(false),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);const started=useRef(0),base=useRef(0);
 useEffect(()=>{if(!running)return;started.current=Date.now();const tick=window.setInterval(()=>setSeconds(base.current+Math.floor((Date.now()-started.current)/1000)),1000);return()=>window.clearInterval(tick)},[running]);
 const minutes=Math.floor(seconds/60);const clock=String(Math.floor(minutes/60)).padStart(2,'0')+':'+String(minutes%60).padStart(2,'0');
 return <section className="bento-card bento-timer"><header><h2>Time tracker</h2><button className="round-button" aria-label="Save tracked time" disabled={!onSave||seconds<60||running||saving} onClick={()=>{setSaving(true);void onSave?.(Math.floor(seconds/60)).then(()=>{setMessage('Time saved as a draft.');setSeconds(0);base.current=0}).catch(()=>setMessage('Time could not be saved. Your session is retained.')).finally(()=>setSaving(false))}}><ArrowUpRight size={18}/></button></header><div className="timer-dial" style={{'--timer-angle':Math.min(360,seconds/3600*360)+'deg'} as CSSProperties}><i className="timer-ticks" aria-hidden="true"/><div><output aria-label="Tracked session time">{clock}</output><span>{running?'Tracking':'Paused'} · {String(seconds%60).padStart(2,'0')}s</span></div></div><footer><button className="round-button" aria-label={running?'Pause timer':'Start timer'} onClick={()=>{if(running)base.current=seconds;setRunning(v=>!v)}}>{running?<Pause size={18}/>:<Play size={18}/>}</button><button className="round-button" aria-label="Reset timer" onClick={()=>{setRunning(false);base.current=0;setSeconds(0);setMessage('Timer reset.')}}><RotateCcw size={18}/></button><button className="round-button alarm-button" aria-label="Break reminder" aria-pressed={alarm} onClick={()=>setAlarm(v=>!v)}><Bell size={18}/></button></footer><p role="status" className="timer-note">{message||(alarm&&seconds>=1500?'Take a break.':onSave?'Save a completed minute to your draft timesheet.':'Personal session · not saved to a timesheet.')}</p></section>
}
export function TaskPanel({tasks,onToggle,onOpen}:{tasks:BentoTask[];onToggle:(id:string)=>void;onOpen:()=>void}){
 const done=tasks.filter(t=>t.done).length,percent=tasks.length?Math.round(done/tasks.length*100):0;
 return <section className="bento-card bento-onboarding"><header><h2>Onboarding</h2><strong>{percent}%</strong></header><div className="onboarding-phases">{['Paperwork','Setup','Team'].map((v,i)=>{const group=tasks.filter((_,n)=>n%3===i),p=group.length?Math.round(group.filter(t=>t.done).length/group.length*100):0;return <div key={v}><span>{p}%</span><div className={p?'active':''}>{v}</div></div>})}</div><div className="onboarding-tasks"><header><h3>Onboarding tasks</h3><strong>{done}/{tasks.length}</strong></header><div className="task-scroll" tabIndex={0} aria-label="Onboarding tasks">{tasks.map((t,i)=><label key={t.id} className={t.done?'done':''}><span className="task-icon">{i+1}</span><span><strong>{t.title}</strong><small>{t.due||'No due date'}</small></span><input aria-label={'Complete '+t.title} type="checkbox" checked={t.done} onChange={()=>onToggle(t.id)}/></label>)}{!tasks.length&&<p>No onboarding tasks assigned.</p>}</div><button onClick={onOpen}>Manage tasks <ArrowUpRight size={14}/></button></div></section>
}
