import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Bell,BriefcaseBusiness,ChevronDown,FileText,LogOut,Settings,UserRound,Users} from 'lucide-react';
import {api} from './api';
import {BentoTask,CalendarEvent,dayKey,SessionTimer,TaskPanel,WeekCalendar,WeeklyGraph} from './BentoElements';
import {Command,demoHR,editDemoHR,Employee,emptyHR,HRContext,Payroll} from './hrDemo';
import type {WorkspaceTheme} from './theme';

function money(cents:number){return new Intl.NumberFormat('en-MY',{style:'currency',currency:'MYR'}).format(cents/100)}
function saveFile(name:string,body:string){const url=URL.createObjectURL(new Blob([body],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const cleanCSV=(v:unknown)=>'"'+String(v??'').replace(/^[=+@-]/,"'").replaceAll('"','""')+'"';
export function HRWorkspace({demo=false,staffDemo=false,invitedDemo=false,embedded=false,csrf='',locale='en',theme='light',setTheme,onCareer,onExit,onViewChange,onContext,navigationRequest}:{demo?:boolean;staffDemo?:boolean;invitedDemo?:boolean;embedded?:boolean;csrf?:string;locale?:'en'|'ms';theme?:WorkspaceTheme;setTheme?:(v:WorkspaceTheme)=>void;onCareer:()=>void;onExit?:()=>void;onViewChange?:(view:string)=>void;onContext?:(data:HRContext|null)=>void;navigationRequest?:{view:string;sequence:number}}){
 const [data,setData]=useState<HRContext>(()=>demo?demoHR(staffDemo,invitedDemo):emptyHR),[view,setView]=useState('Overview'),[company,setCompany]=useState(''),[month,setMonth]=useState(()=>dayKey(new Date()).slice(0,7)),[employee,setEmployee]=useState(''),[query,setQuery]=useState(''),[team,setTeam]=useState('All'),[selection,setSelection]=useState<string[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[settings,setSettings]=useState(false),[notifications,setNotifications]=useState(false);
 const [timeDay,setTimeDay]=useState(dayKey(new Date())),[timeMinutes,setTimeMinutes]=useState(60),[timeTitle,setTimeTitle]=useState(''),[leaveDay,setLeaveDay]=useState(dayKey(new Date())),[leaveEnd,setLeaveEnd]=useState(dayKey(new Date())),[leaveKind,setLeaveKind]=useState('annual'),[leaveReason,setLeaveReason]=useState(''),[taskTitle,setTaskTitle]=useState(''),[eventTitle,setEventTitle]=useState(''),[eventDate,setEventDate]=useState(''),[base,setBase]=useState('4850.00'),[allowance,setAllowance]=useState('300.00'),[deduction,setDeduction]=useState('500.00'),[payId,setPayId]=useState<string|null>(null),[payRevision,setPayRevision]=useState(0),[eventDetail,setEventDetail]=useState<CalendarEvent|null>(null),[endReason,setEndReason]=useState('');
 const [contextReady,setContextReady]=useState(demo);
 useEffect(()=>{onContext?.(contextReady?{...data,loaded_month:month}:null)},[data,contextReady,month,onContext]);
 useEffect(()=>{if(navigationRequest)setView(navigationRequest.view)},[navigationRequest]);
 const loaded=useRef(0),operation=useRef(false),retry=useRef<{fingerprint:string;key:string}|null>(null);const mine=data.mine.find(e=>e.state!=='ended');const selected=data.employees.find(e=>e.id===employee)||data.employees[0];const current=data.employees.find(e=>e.id===mine?.id)||selected;const own=!!selected&&data.mine.some(e=>e.id===selected.id);const staff=data.hr||data.payroll_admin;
 useEffect(()=>{if(demo)return;const generation=++loaded.current;void api<HRContext>('/hr/context?'+new URLSearchParams({company,month})).then(v=>{if(loaded.current===generation){setData(v);setContextReady(true);setMessage('')}}).catch(()=>{if(loaded.current===generation){setData(emptyHR);setContextReady(false);setMessage('Company workspace unavailable. HR migration, employment or staff grants may still need setup.')}});return()=>{loaded.current++}},[demo,company,month]);
 function navigate(next:string){setView(next);onViewChange?.(next)}
 async function refresh(){if(!demo){const latest=await api<HRContext>('/hr/context?'+new URLSearchParams({company,month}));setData(latest);setContextReady(true)}}
 async function command(c:Command){
  if(operation.current)throw Error('Wait for the current HR change.');
  operation.current=true;setBusy(true);setMessage('');
  try{
   if(demo)setData(editDemoHR(data,c));
   else{
    const fingerprint=JSON.stringify(c);
    if(retry.current?.fingerprint!==fingerprint)retry.current={fingerprint,key:crypto.randomUUID()};
    await api('/hr/command',{method:'POST',body:JSON.stringify({expected_revision:0,...c,idempotency_key:retry.current.key})},csrf);
    await refresh();retry.current=null;
   }
   setMessage(demo?'Sample HR record updated. No external action performed.':'HR record saved.');
  }catch(e){setMessage(String(e));throw e}finally{operation.current=false;setBusy(false)}
 }

 function act(c:Command){void command(c).catch(()=>{})}
 const personTasks=data.tasks.filter(t=>t.employee_id===current?.id);const tasks:BentoTask[]=personTasks.map(t=>({id:t.id,title:t.title,due:t.due||'',done:t.completed}));
 const personTimes=data.times.filter(t=>t.employee_id===current?.id);const weekly=Array.from({length:7},(_,i)=>{const d=new Date(dayKey(new Date())+'T12:00:00+08:00');d.setUTCDate(d.getUTCDate()-6+i);return personTimes.filter(t=>t.day===dayKey(d)&&t.state!=='rejected').reduce((n,t)=>n+t.minutes/60,0)});
 const events:CalendarEvent[]=data.events.filter(t=>staff||t.employee_id===mine?.id).map(e=>({...e,kind:e.employee_id===mine?.id?'personal':'team'}));
 const people=data.employees.filter(e=>(team==='All'||e.department===team)&&(e.name+' '+e.title).toLowerCase().includes(query.toLowerCase()));const pay=data.payroll.filter(p=>p.period===month&&(staff?p.employee_id===selected?.id:p.employee_id===mine?.id));
 const personPay=data.payroll.find(p=>p.employee_id===current?.id&&p.period===month);const Wrapper=embedded?'section':'main';
 function payslip(p:Payroll){const name=data.employees.find(e=>e.id===p.employee_id)?.name||'Employee';saveFile('kerjaos-'+p.period+'-payslip.txt',['KerjaOS · Payroll ledger',data.companies.find(c=>c.id===data.company_id)?.name||'Company',name,p.period,'Currency: MYR','Base: '+money(p.base_cents),'Allowances: '+money(p.allowance_cents),'Deductions: '+money(p.deduction_cents),'Net: '+money(p.net_cents),'State: '+p.state,'Manual reviewed figures. This document does not confirm bank payment.'].join('\n'))}
 function exportPayroll(){saveFile('kerjaos-payroll-'+month+'.csv',[['Employee','Period','Currency','Base','Allowances','Deductions','Net','State'],...data.payroll.filter(p=>p.period===month).map(p=>[data.employees.find(e=>e.id===p.employee_id)?.name,p.period,'MYR',(p.base_cents/100).toFixed(2),(p.allowance_cents/100).toFixed(2),(p.deduction_cents/100).toFixed(2),(p.net_cents/100).toFixed(2),p.state])].map(r=>r.map(cleanCSV).join(',')).join('\r\n'))}
 return <Wrapper className={(embedded?'':'foundation ')+ 'hr-shell'} data-theme={theme} aria-label="HR workspace">
 <header className="hr-header"><a className="hr-brand" href="#" onClick={e=>{e.preventDefault();navigate('Overview')}}><span/>KerjaOS</a><nav aria-label="HR navigation" className="hr-pill-nav">{['Overview','People','Payroll'].map(v=><button key={v} aria-current={view===v?'page':undefined} onClick={()=>navigate(v)}>{v}</button>)}</nav><div className="hr-header-actions"><button aria-expanded={settings} onClick={()=>setSettings(v=>!v)}><Settings size={17}/>Settings</button><button className="round-button notification-button" aria-label={'Notifications, '+tasks.filter(t=>!t.done).length+' pending tasks'} aria-expanded={notifications} onClick={()=>setNotifications(v=>!v)}><Bell size={17}/>{tasks.some(t=>!t.done)&&<span>{tasks.filter(t=>!t.done).length}</span>}</button><button className="round-button" aria-label="Open career workspace" onClick={onCareer}><UserRound size={17}/></button></div></header>
 {settings&&<section className="hr-settings" aria-label="HR settings"><label>Theme<select aria-label="HR theme" value={theme} onChange={e=>setTheme?.(e.target.value as WorkspaceTheme)}><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Company<select value={company||data.company_id||''} onChange={e=>setCompany(e.target.value)}>{data.companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button onClick={onCareer}>Recruitment & career tools</button>{onExit&&<button onClick={onExit}><LogOut size={15}/>Sign out</button>}</section>}
 {notifications&&<section className="hr-notifications" aria-label="HR notifications"><h2>Next steps</h2>{tasks.filter(t=>!t.done).map(t=><button key={t.id} onClick={()=>{navigate('Tasks');setNotifications(false)}}>{t.title}<small>{t.due}</small></button>)}{!tasks.some(t=>!t.done)&&<p>You're all caught up.</p>}</section>}
 <p role="status" className="hr-status">{message}</p>
 {!data.companies.length?<section className="bento-card"><h1>Company workspace</h1><p>Your employee dashboard becomes available after a finalized hire and company invitation. Staff need an explicit HR or payroll grant.</p><button onClick={onCareer}>Return to recruitment</button><button disabled={busy} onClick={()=>void refresh().catch(()=>setMessage('HR setup is still pending.'))}>Refresh company access</button></section>:<>
 {mine?.state==='invited'&&<section className="company-invitation"><h1>Welcome to {data.companies.find(c=>c.id===data.company_id)?.name}</h1><p>Your accepted, finalized hire has a company invitation for {mine.title}. Join to open your employee dashboard; your other applications stay in the career workspace.</p><button disabled={busy} onClick={()=>act({action:'join',employee_id:mine.id,expected_revision:mine.revision})}>Join company</button></section>}
 {view==='Overview'&&<><h1 className="hr-greeting">{locale==='ms'?'Selamat datang':'Good morning'}, {current?.name.split(' ')[0]||'team'}</h1><section className="hiring-rail" aria-label="Company overview"><div className="rail-meters">{[{label:'Onboarding',value:tasks.length?Math.round(tasks.filter(t=>t.done).length/tasks.length*100):0},{label:'Active team',value:data.employees.length?Math.round(data.employees.filter(e=>e.state==='active').length/data.employees.length*100):0},{label:'Approved time',value:personTimes.length?Math.round(personTimes.filter(t=>t.state==='approved').length/personTimes.length*100):0},{label:'Leave',value:data.leaves.length?Math.round(data.leaves.filter(l=>l.state==='approved').length/data.leaves.length*100):0}].map((m,i)=><div className={'rail-meter rail-'+i} key={m.label}><span>{m.label}</span><div><strong>{m.value}%</strong></div></div>)}</div><div className="rail-numbers"><div><strong>{data.employees.filter(e=>e.state==='active').length}</strong><span><Users size={13}/>Team</span></div><div><strong>{data.employees.filter(e=>e.state==='invited').length}</strong><span><BriefcaseBusiness size={13}/>Joining</span></div><div><strong>{data.tasks.length}</strong><span><FileText size={13}/>Tasks</span></div></div></section>
 <div className="hr-bento-grid"><article className="bento-profile">{demo?<img src="/kerjaos-demo-portrait.png" alt="Original fictional demo employee portrait"/>:<div className="employee-initials" aria-hidden="true">{current?.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</div>}<div><h2>{current?.name||'Your company'}</h2><p>{current?.title||'Employee'}</p>{personPay&&<span>{money(personPay.net_cents)}</span>}</div></article><WeeklyGraph values={weekly} label="h · tracked work" onOpen={()=>navigate('Timesheets')}/><SessionTimer onSave={mine?.state==='active'?minutes=>command({action:'time_create',employee_id:mine.id,day:dayKey(new Date()),minutes,title:'Tracked work session'}).then(()=>{}):undefined}/><TaskPanel tasks={tasks} onToggle={id=>{const t=personTasks.find(t=>t.id===id);if(t)act({action:'task_complete',employee_id:t.employee_id,id:t.id,expected_revision:t.revision,completed:!t.completed})}} onOpen={()=>navigate('Tasks')}/><section className="bento-card bento-accordions">{[{name:'Company & role',text:(data.companies.find(c=>c.id===data.company_id)?.name||'Company')+' · '+(current?.department||''),action:'People'},{name:'Documents & onboarding',text:tasks.filter(t=>!t.done).length+' next steps to complete',action:'Tasks'},{name:'Compensation',text:personPay?money(personPay.net_cents)+' · '+personPay.state:'No issued payroll record',action:'Payroll'},{name:'Leave & benefits',text:'Annual, sick and unpaid leave requests',action:'Leave'}].map((v,i)=><details key={v.name} open={i===1}><summary>{v.name}<ChevronDown size={15}/></summary><p>{v.text}</p><button onClick={()=>navigate(v.action)}>Open {v.action.toLowerCase()} <ArrowUpRight size={15}/></button></details>)}</section><WeekCalendar events={events} onEvent={setEventDetail} onNew={data.hr?date=>{setEventDate(date.slice(0,16));navigate('Calendar')}:undefined} locale={locale}/></div><div className="hr-secondary-actions"><button onClick={()=>navigate('Timesheets')}>Timesheets</button><button onClick={()=>navigate('Leave')}>Leave requests</button><button onClick={()=>navigate('Tasks')}>Onboarding</button><button onClick={()=>navigate('Calendar')}>Calendar</button><button onClick={onCareer}>Recruitment & career tools</button></div></>}
 {view==='People'&&<><div className="hr-view-heading"><h1>People</h1><label className="people-search">Search<input aria-label="Search people" placeholder="Search by name or role" value={query} onChange={e=>setQuery(e.target.value)}/></label><button onClick={onCareer}>+ Hire through recruitment</button></div><div className="people-filters">{['All',...new Set(data.employees.map(e=>e.department))].map(v=><button aria-pressed={team===v} key={v} onClick={()=>setTeam(v)}>{v} <span>{data.employees.filter(e=>v==='All'||e.department===v).length}</span></button>)}</div><div className="bento-card people-table-wrap" tabIndex={0}><table><caption>Company directory · {selection.length} selected</caption><thead><tr><th>Select</th><th>Name</th><th>Role</th><th>Team</th><th>Started</th><th>Status</th><th>Profile</th></tr></thead><tbody>{people.map(e=><tr key={e.id} className={selection.includes(e.id)?'selected':''}><td><input type="checkbox" aria-label={'Select '+e.name} checked={selection.includes(e.id)} onChange={()=>setSelection(v=>v.includes(e.id)?v.filter(id=>id!==e.id):[...v,e.id])}/></td><th scope="row"><span className="person-avatar">{e.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span>{e.name}</th><td>{e.title}</td><td>{e.department}</td><td>{e.start_date}</td><td><span className={'person-status '+e.state}>{e.state}</span></td><td><button onClick={()=>{setEmployee(e.id);navigate('Employee')}}>View profile</button></td></tr>)}{!people.length&&<tr><td colSpan={7}>No people match these filters.</td></tr>}</tbody></table></div></>}
 {view==='Payroll'&&<><div className="hr-view-heading"><h1>{staff?'Payroll':'My payslips'}</h1><label>Month<input type="month" aria-label="Payroll month" value={month} onChange={e=>{setMonth(e.target.value);setPayId(null)}}/></label>{data.payroll_admin&&<button onClick={exportPayroll}>Export payroll CSV</button>}</div><div className="payroll-layout"><section className="bento-card payroll-roster"><h2>Team</h2>{data.employees.map(e=><button key={e.id} aria-pressed={selected?.id===e.id} onClick={()=>{setEmployee(e.id);setPayId(null)}}><span className="person-avatar">{e.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><span>{e.name}<small>{e.title}</small></span></button>)}</section><section className="bento-card payroll-month"><h2>{money(pay.reduce((n,p)=>n+p.net_cents,0))}<small>{month}</small></h2><div className="payroll-rail"><div>Base <strong>{money(pay.reduce((n,p)=>n+p.base_cents,0))}</strong></div><div>Allowances <strong>{money(pay.reduce((n,p)=>n+p.allowance_cents,0))}</strong></div><div>Deductions <strong>{money(pay.reduce((n,p)=>n+p.deduction_cents,0))}</strong></div></div><MonthView month={month} times={data.times.filter(t=>t.employee_id===selected?.id)} leaves={data.leaves.filter(l=>l.employee_id===selected?.id)}/>{pay.map(p=><article className="payroll-record" key={p.id}><strong>{p.state} · {money(p.net_cents)}</strong>{data.payroll_admin&&p.state==='draft'&&<><button onClick={()=>{setPayId(p.id);setPayRevision(p.revision);setBase((p.base_cents/100).toFixed(2));setAllowance((p.allowance_cents/100).toFixed(2));setDeduction((p.deduction_cents/100).toFixed(2))}}>Edit draft</button><button disabled={busy||own} onClick={()=>act({action:'payroll_approve',employee_id:p.employee_id,id:p.id,expected_revision:p.revision})}>Approve payroll</button></>}{data.payroll_admin&&p.state==='approved'&&<button disabled={busy||own} onClick={()=>act({action:'payroll_issue',employee_id:p.employee_id,id:p.id,expected_revision:p.revision})}>Issue payslip</button>}{p.state==='issued'&&<button onClick={()=>payslip(p)}>Download payslip</button>}</article>)}{!pay.length&&<p>No payroll record available for this person/month.</p>}</section><section className="bento-card payroll-profile"><div className="person-avatar large">{selected?.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</div><h2>{selected?.name}</h2><p>{selected?.title} · {selected?.department}</p><dl><dt>Company</dt><dd>{data.companies.find(c=>c.id===data.company_id)?.name}</dd><dt>Employment</dt><dd>{selected?.state}</dd><dt>Started</dt><dd>{selected?.start_date}</dd></dl><h3>This month</h3><p>Approved time</p><strong>{(data.times.filter(t=>t.employee_id===selected?.id&&t.day.startsWith(month)&&t.state==='approved').reduce((n,t)=>n+t.minutes,0)/60).toFixed(1)} hours</strong><div className="person-meters">{[
 {label:'Approved hours',done:data.times.filter(t=>t.employee_id===selected?.id&&t.day.startsWith(month)&&t.state==='approved').reduce((n,t)=>n+t.minutes/60,0),total:data.times.filter(t=>t.employee_id===selected?.id&&t.day.startsWith(month)&&t.state!=='rejected').reduce((n,t)=>n+t.minutes/60,0),unit:'h'},
 {label:'Onboarding',done:data.tasks.filter(t=>t.employee_id===selected?.id&&t.completed).length,total:data.tasks.filter(t=>t.employee_id===selected?.id).length,unit:'tasks'},
 {label:'Approved leave',done:data.leaves.filter(t=>t.employee_id===selected?.id&&t.state==='approved').length,total:data.leaves.filter(t=>t.employee_id===selected?.id).length,unit:'requests'}
 ].map(m=><div key={m.label}><span>{m.label}<strong>{Number(m.done.toFixed(1))} / {Number(m.total.toFixed(1))} {m.unit}</strong></span><progress aria-label={m.label+' for '+selected?.name} value={m.done} max={m.total||1}/></div>)}</div><p>Issued documents</p>{pay.filter(p=>p.state==='issued').map(p=><button key={p.id} onClick={()=>payslip(p)}><FileText size={14}/>Payslip · {p.period}</button>)}</section></div>{data.payroll_admin&&selected?.state==='active'&&<form className="bento-card hr-form" onSubmit={e=>{e.preventDefault();const cents=(value:string)=>Math.round(Number(value)*100);void command({action:'payroll_save',employee_id:selected.id,...(payId?{id:payId,expected_revision:payRevision}:{}),period:month,base_cents:cents(base),allowance_cents:cents(allowance),deduction_cents:cents(deduction)}).then(()=>setPayId(null)).catch(()=>{})}}><h2>{payId?'Edit draft':'New payroll draft'}</h2><label>Base earnings (MYR)<input required type="number" min="0" max="999999.99" step="0.01" value={base} onChange={e=>setBase(e.target.value)}/></label><label>Allowances (MYR)<input required type="number" min="0" max="999999.99" step="0.01" value={allowance} onChange={e=>setAllowance(e.target.value)}/></label><label>Reviewed deductions (MYR)<input required type="number" min="0" max="999999.99" step="0.01" value={deduction} onChange={e=>setDeduction(e.target.value)}/></label><p>Manually reviewed MYR figures. Statutory calculations and bank transfers are not automated. Issued means a payslip record, not money paid.</p><button disabled={busy}>Save payroll draft</button></form>}</>}
 {view==='Timesheets'&&<section className="bento-card"><h1>Timesheets</h1>{mine?.state==='active'&&<form className="hr-form" onSubmit={e=>{e.preventDefault();void command({action:'time_create',employee_id:mine.id,day:timeDay,minutes:timeMinutes,title:timeTitle}).then(()=>setTimeTitle('')).catch(()=>{})}}><label>Work date<input type="date" aria-label="Work date" required max={dayKey(new Date())} min={mine.start_date} value={timeDay} onChange={e=>setTimeDay(e.target.value)}/></label><label>Minutes worked<input type="number" aria-label="Minutes worked" required min={1} max={1440} value={timeMinutes} onChange={e=>setTimeMinutes(Number(e.target.value))}/></label><label>Work summary<input maxLength={120} value={timeTitle} onChange={e=>setTimeTitle(e.target.value)}/></label><button disabled={busy}>Save time draft</button></form>}<div className="hr-table-scroll" tabIndex={0}><table><caption>Submitted time requires a separate HR reviewer</caption><thead><tr><th>Employee</th><th>Date</th><th>Hours</th><th>State</th><th>Actions</th></tr></thead><tbody>{data.times.map(t=><tr key={t.id}><td>{data.employees.find(e=>e.id===t.employee_id)?.name}</td><td>{t.day}</td><td>{(t.minutes/60).toFixed(2)}</td><td>{t.state}</td><td>{data.mine.some(e=>e.id===t.employee_id)&&['draft','rejected'].includes(t.state)&&<button disabled={busy} onClick={()=>act({action:'time_submit',employee_id:t.employee_id,id:t.id,expected_revision:t.revision})}>Submit time</button>}{data.hr&&!data.mine.some(e=>e.id===t.employee_id)&&t.state==='submitted'&&<><button disabled={busy} onClick={()=>act({action:'time_approve',employee_id:t.employee_id,id:t.id,expected_revision:t.revision})}>Approve time</button><button disabled={busy} onClick={()=>act({action:'time_reject',employee_id:t.employee_id,id:t.id,expected_revision:t.revision})}>Reject time</button></>}</td></tr>)}</tbody></table></div></section>}
 {view==='Leave'&&<section className="bento-card"><h1>Leave requests</h1><p>Dates count calendar days; company entitlement and statutory policy need separate review. Do not include medical details in your reason.</p>{mine?.state==='active'&&<form className="hr-form" onSubmit={e=>{e.preventDefault();void command({action:'leave_create',employee_id:mine.id,day:leaveDay,end_day:leaveEnd,leave_kind:leaveKind,reason:leaveReason}).then(()=>setLeaveReason('')).catch(()=>{})}}><label>From<input aria-label="Leave from" required type="date" min={mine.start_date} value={leaveDay} onChange={e=>setLeaveDay(e.target.value)}/></label><label>Until<input aria-label="Leave until" required type="date" min={leaveDay} value={leaveEnd} onChange={e=>setLeaveEnd(e.target.value)}/></label><label>Leave type<select value={leaveKind} onChange={e=>setLeaveKind(e.target.value)}>{['annual','sick','unpaid'].map(v=><option key={v}>{v}</option>)}</select></label><label>Reason<input aria-label="Leave reason" required minLength={3} maxLength={500} value={leaveReason} onChange={e=>setLeaveReason(e.target.value)}/></label><button disabled={busy}>Request leave</button></form>}{data.leaves.map(l=><article className="hr-record" key={l.id}><strong>{data.employees.find(e=>e.id===l.employee_id)?.name} · {l.kind}</strong><p>{l.day} – {l.end_day} · {l.state}</p>{l.state==='pending'&&(data.mine.some(e=>e.id===l.employee_id)?<button onClick={()=>act({action:'leave_withdraw',employee_id:l.employee_id,id:l.id,expected_revision:l.revision})}>Withdraw leave</button>:data.hr?<><button onClick={()=>act({action:'leave_approve',employee_id:l.employee_id,id:l.id,expected_revision:l.revision})}>Approve leave</button><button onClick={()=>act({action:'leave_reject',employee_id:l.employee_id,id:l.id,expected_revision:l.revision})}>Reject leave</button></>:null)}</article>)}</section>}
 {view==='Tasks'&&<section className="bento-card"><h1>Onboarding tasks</h1>{data.hr&&selected&&<form className="hr-form" onSubmit={e=>{e.preventDefault();void command({action:'task_create',employee_id:selected.id,title:taskTitle,day:dayKey(new Date())}).then(()=>setTaskTitle('')).catch(()=>{})}}><label>Employee<select aria-label="Task employee" value={selected.id} onChange={e=>setEmployee(e.target.value)}>{data.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Task title<input required minLength={2} maxLength={120} value={taskTitle} onChange={e=>setTaskTitle(e.target.value)}/></label><button disabled={busy}>Assign task</button></form>}{data.tasks.map(t=><label className="hr-task-line" key={t.id}><input type="checkbox" checked={t.completed} onChange={()=>act({action:'task_complete',employee_id:t.employee_id,id:t.id,expected_revision:t.revision,completed:!t.completed})}/>{t.title}<small>{data.employees.find(e=>e.id===t.employee_id)?.name} · {t.due||'No due date'}</small></label>)}</section>}
 {view==='Calendar'&&<><h1>Company calendar</h1><WeekCalendar events={events} onEvent={setEventDetail} onNew={data.hr?date=>setEventDate(date.slice(0,16)):undefined} locale={locale}/>{data.hr&&selected&&<form className="bento-card hr-form" onSubmit={e=>{e.preventDefault();const start=new Date(eventDate+':00+08:00');act({action:'event_create',employee_id:selected.id,title:eventTitle,starts_at:start.toISOString(),ends_at:new Date(start.getTime()+3600000).toISOString()})}}><label>Employee<select value={selected.id} onChange={e=>setEmployee(e.target.value)}>{data.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Event title<input required minLength={2} maxLength={120} value={eventTitle} onChange={e=>setEventTitle(e.target.value)}/></label><label>Starts at (Kuala Lumpur)<input required type="datetime-local" value={eventDate} onChange={e=>setEventDate(e.target.value)}/></label><button disabled={busy}>Schedule company event</button></form>}</>}
 {view==='Employee'&&selected&&<section className="bento-card"><h1>{selected.name}</h1><p>{selected.title} · {selected.department} · {selected.state}</p><p>Started {selected.start_date}</p><button onClick={()=>navigate('Payroll')}>Payroll records</button><button onClick={()=>navigate('Tasks')}>Onboarding tasks</button>{data.hr&&!own&&selected.state!=='ended'&&<form className="hr-form" onSubmit={e=>{e.preventDefault();void command({action:'employment_end',employee_id:selected.id,expected_revision:selected.revision,reason:endReason}).then(()=>setEndReason('')).catch(()=>{})}}><label>Offboarding reason<input required minLength={5} maxLength={500} value={endReason} onChange={e=>setEndReason(e.target.value)}/></label><button disabled={busy}>End company employment</button></form>}</section>}
 </>}
 {eventDetail&&<div className="hr-event-detail" role="dialog" aria-modal="false" aria-label="Calendar event details" onKeyDown={e=>{if(e.key==='Escape')setEventDetail(null)}}><h2>{eventDetail.title}</h2><p>{new Date(eventDetail.starts_at).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur'})} · Kuala Lumpur</p><button autoFocus onClick={()=>setEventDetail(null)}>Close event details</button></div>}
 <footer className="hr-footer"><span>{demo?'Invented sample company · Changes reset on sign out':data.companies.find(c=>c.id===data.company_id)?.name||'Company HR'} · {staff?'Management workspace':'Employee workspace'}</span>{demo&&<span>Demo figures · no payment or email</span>}</footer>
 </Wrapper>
}
function MonthView({month,times,leaves}:{month:string;times:HRContext['times'];leaves:HRContext['leaves']}){
 const [selected,setSelected]=useState('');const date=new Date(month+'-01T12:00:00+08:00');if(!Number.isFinite(date.getTime()))return null;const count=new Date(date.getUTCFullYear(),date.getUTCMonth()+1,0).getDate(),offset=(date.getUTCDay()+6)%7;
 return <><div className="month-weekdays">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(v=><span key={v}>{v}</span>)}</div><div className="month-grid">{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:count},(_,i)=>{const day=month+'-'+String(i+1).padStart(2,'0'),minutes=times.filter(t=>t.day===day&&t.state!=='rejected').reduce((n,t)=>n+t.minutes,0),leave=leaves.some(l=>l.state==='approved'&&l.day<=day&&l.end_day>=day);return <button key={day} aria-pressed={selected===day} aria-label={day+(leave?' Leave':minutes?' '+(minutes/60).toFixed(1)+' hours':' No time recorded')} onClick={()=>setSelected(day)}><span>{i+1}</span>{leave?<small className="month-leave">Leave</small>:minutes?<small>{(minutes/60).toFixed(1)}h</small>:null}</button>})}</div>{selected&&<p role="status" className="month-detail">{selected}: {(times.filter(t=>t.day===selected&&t.state!=='rejected').reduce((n,t)=>n+t.minutes,0)/60).toFixed(1)} tracked hours.</p>}</>
}
