import { useEffect, useState } from 'react';
import { api } from './api';
import type { ApplicationRow } from './ApplicationDashboard';
type Case={id:string;application_id:string;route:string;synthetic:boolean;state:string;version:number;reason_code?:string;assigned:boolean;quality_hint?:string;expires_at?:string;shared_assertion?:{id:string;method:string;reviewer_id:string;verified_at:string;expires_at:string;revoked:boolean}};
type Assertion={id:string;method:string;verified_at:string;expires_at:string;revoked:boolean};
type Props={applications:ApplicationRow[];csrf:string;locale:'en'|'ms';reviewer:boolean;reload:()=>Promise<void>};
export function IdentityWorkspace({applications,csrf,locale,reviewer,reload}:Props){
 const bm=locale==='ms',t=(en:string,ms:string)=>bm?ms:en;
 const [cases,setCases]=useState<Case[]>([]),[queue,setQueue]=useState<Case[]>([]),[assertions,setAssertions]=useState<Assertion[]>([]);
 const [policy,setPolicy]=useState<{version:string;text:Record<string,string>;real_capture_enabled:boolean}|null>(null);
 const [application,setApplication]=useState(''),[route,setRoute]=useState('mykad'),[agree,setAgree]=useState(false),[synthetic,setSynthetic]=useState(true);
 const [assertion,setAssertion]=useState(''),[shared,setShared]=useState<string[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[links,setLinks]=useState<Record<string,string>>({});
 const [review,setReview]=useState<{row:Case;decision:string}|null>(null),[reason,setReason]=useState('review_completed'),[attested,setAttested]=useState(false);
 async function refresh(){const [c,a,p,s]=await Promise.all([api<Case[]>('/identity/cases'),api<Assertion[]>('/identity/assertions'),api<any>('/identity/policy'),api<{id:string;revoked:boolean}[]>('/identity/shares')]);setCases(c);setAssertions(a);setPolicy(p);setShared(s.filter(row=>!row.revoked).map(row=>row.id));if(reviewer)setQueue(await api<Case[]>('/identity/review-queue'));}
 useEffect(()=>{void refresh().catch(e=>setMessage(String(e)));},[applications,reviewer]);
 async function work(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();await refresh();await reload();}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 const eligible=applications.filter(a=>a.stage==='P2'&&!['withdrawn','rejected','job_closed','hired'].includes(a.status));
 async function consent(){if(!policy||!application||!agree)throw Error(t('Read and accept the employer-specific consent.','Baca dan terima persetujuan khusus majikan.'));await api('/identity/consents',{method:'POST',body:JSON.stringify({application_id:application,version:policy.version,agree})},csrf);}
 return <section aria-label={t('Identity review','Semakan identiti')}>
 <h2>{t('Identity review','Semakan identiti')}</h2><p>{t('Manual review is not an official registry check. No face or liveness capture. Synthetic evidence is labelled as a demo.','Semakan manual bukan semakan daftar rasmi. Tiada rakaman muka atau liveness. Bukti sintetik dilabel sebagai demo.')}</p>
 <p role="status">{message}</p>
 {eligible.length>0 && <fieldset><legend>{t('Consent and document route','Persetujuan dan laluan dokumen')}</legend>
 <label>{t('Identity application','Permohonan identiti')}<select value={application} onChange={e=>{setApplication(e.target.value);setAgree(false);}}><option value="">{t('Select application','Pilih permohonan')}</option>{eligible.map(a=><option key={a.id} value={a.id}>{a.job_title||a.job_id} · {a.id}</option>)}</select></label>
 <p>{policy?.text[locale]}</p><label><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)} />{t('I consent for the selected application and employer','Saya bersetuju untuk permohonan dan majikan dipilih')}</label>
 <label>{t('Document route','Laluan dokumen')}<select value={route} onChange={e=>setRoute(e.target.value)}><option value="mykad">MyKad</option><option value="passport">{t('Passport','Pasport')}</option><option value="alternative">{t('Alternative human review — no upload','Semakan manusia alternatif — tiada muat naik')}</option></select></label>
 <label><input type="checkbox" checked={synthetic} disabled={!policy?.real_capture_enabled} onChange={e=>setSynthetic(e.target.checked)} />{t('Synthetic test evidence only','Bukti ujian sintetik sahaja')}</label>
 <button disabled={busy||!agree||!application} onClick={()=>void work(async()=>{await consent();await api('/identity/cases',{method:'POST',body:JSON.stringify({application_id:application,route,synthetic})},csrf);setMessage(t('Case opened. An assigned qualified reviewer must approve it.','Kes dibuka. Penyemak berkelayakan yang ditugaskan mesti meluluskannya.'));})}>{t('Start identity review','Mulakan semakan identiti')}</button>
 {assertions.some(a=>!a.revoked&&new Date(a.expires_at)>new Date())&&<><label>{t('Reusable assertion','Pengesahan untuk penggunaan semula')}<select value={assertion} onChange={e=>setAssertion(e.target.value)}><option value="">{t('Select assertion','Pilih pengesahan')}</option>{assertions.filter(a=>!a.revoked).map(a=><option key={a.id} value={a.id}>{a.method} · {a.id}</option>)}</select></label>
 <button disabled={busy||!agree||!application||!assertion} onClick={()=>void work(async()=>{await consent();const result=await api<{id:string}>('/identity/shares',{method:'POST',body:JSON.stringify({assertion_id:assertion,application_id:application})},csrf);setShared(s=>[...s,result.id]);setMessage(t('Minimal assertion shared; receiving reviewer approval still required.','Pengesahan minimum dikongsi; kelulusan penyemak penerima masih diperlukan.'));})}>{t('Share with fresh employer consent','Kongsi dengan persetujuan baharu majikan')}</button></>}
 </fieldset>}
 <ul>{cases.map(c=><li key={c.id}><h3>{c.application_id} · {c.state}</h3><p>{c.route} · {c.synthetic?t('SYNTHETIC DEMO','DEMO SINTETIK'):t('Manual evidence','Bukti manual')} · {c.assigned?t('Reviewer assigned','Penyemak ditugaskan'):t('Awaiting qualified reviewer assignment','Menunggu penyemak berkelayakan')}</p><p>{c.reason_code} {c.quality_hint}</p>
 {c.expires_at&&<p>{t('Document deletion due: ','Dokumen perlu dipadam: ')}{new Date(c.expires_at).toLocaleString(bm?'ms-MY':'en-MY')}</p>}
 {['awaiting_document','needs_review'].includes(c.state)&&['mykad','passport'].includes(c.route)&&<label>{t('Upload identity evidence (PDF/PNG/JPEG, 3 MB)','Muat naik bukti identiti (PDF/PNG/JPEG, 3 MB)')}<input type="file" accept="application/pdf,image/png,image/jpeg" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(!file)return;void work(async()=>{const body=new FormData();body.append('file',file);await api('/identity/cases/'+c.id+'/document',{method:'POST',body},csrf);setMessage(t('Encrypted evidence quarantined for manual review.','Bukti disulitkan dan dikuarantin untuk semakan manual.'));});e.target.value='';}} /></label>}
 {c.route!=='alternative'&&c.route!=='assertion'&&<button disabled={busy} onClick={()=>void work(async()=>{const r=await api<{url:string}>('/identity/cases/'+c.id+'/access',{method:'POST'},csrf);setLinks(s=>({...s,[c.id]:r.url}));})}>{t('Request private document link','Minta pautan dokumen peribadi')}</button>}
 {links[c.id]&&<a href={links[c.id]} target="_blank" rel="noreferrer">{t('Open within 60 seconds','Buka dalam 60 saat')}</a>}
 <button disabled={busy||c.state==='cancelled'} onClick={()=>void work(async()=>{await api('/identity/consent/'+c.application_id+'/revoke',{method:'POST'},csrf);setLinks({});})}>{t('Revoke identity consent','Tarik balik persetujuan identiti')}</button></li>)}</ul>
 <h3>{t('My minimal assertions','Pengesahan minimum saya')}</h3><ul>{assertions.map(a=><li key={a.id}>{a.method} · {a.id} · {t('Expires','Tamat')} {new Date(a.expires_at).toLocaleDateString()} {a.revoked?t('Revoked','Ditarik balik'):''}<button disabled={busy||a.revoked} onClick={()=>void work(async()=>{await api('/identity/assertion/'+a.id+'/revoke',{method:'POST'},csrf);})}>{t('Revoke assertion','Tarik balik pengesahan')}</button></li>)}</ul>
 {shared.map(id=><button key={id} disabled={busy} onClick={()=>void work(async()=>{await api('/identity/sharing/'+id+'/revoke',{method:'POST'},csrf);setShared(s=>s.filter(v=>v!==id));})}>{t('Revoke sharing','Tarik balik perkongsian')} · {id}</button>)}
 {reviewer&&<><h3>{t('Assigned identity reviews','Semakan identiti ditugaskan')}</h3><ul>{queue.map(c=><li key={c.id}>{c.application_id} · {c.state} · {c.synthetic?'SYNTHETIC DEMO':''}<p>{c.quality_hint}</p>
 {c.shared_assertion&&<p>{t('Shared minimal assertion','Pengesahan minimum dikongsi')}: {c.shared_assertion.method} · {c.shared_assertion.reviewer_id} · {c.shared_assertion.verified_at} · {t('Expires','Tamat')} {c.shared_assertion.expires_at} {c.shared_assertion.revoked?t('Revoked','Ditarik balik'):''}</p>}
 {['mykad','passport'].includes(c.route)&&<button disabled={busy} onClick={()=>void work(async()=>{const r=await api<{url:string}>('/identity/cases/'+c.id+'/access',{method:'POST'},csrf);setLinks(s=>({...s,[c.id]:r.url}));})}>{t('Review private evidence','Semak bukti peribadi')}</button>}{links[c.id]&&<a href={links[c.id]} target="_blank" rel="noreferrer">{t('Open within 60 seconds','Buka dalam 60 saat')}</a>}
 {['awaiting_review','evidence_consistent'].includes(c.state)&&<><button disabled={busy} onClick={()=>{setReview({row:c,decision:'needs_review'});setReason('blurred');setAttested(false);}}>{t('Request correction','Minta pembetulan')}</button><button disabled={busy} onClick={()=>{setReview({row:c,decision:'verified_manual'});setReason(c.route==='alternative'?'alternative_completed':'review_completed');setAttested(false);}}>{t('Record manual verification','Rekod pengesahan manual')}</button></>}</li>)}</ul></>}
 {review&&<section role="dialog" aria-label={t('Identity reviewer decision','Keputusan penyemak identiti')}><p>{review.decision} · {review.row.id}</p><label>{t('Review reason','Sebab semakan')}<select value={reason} onChange={e=>setReason(e.target.value)}>{['review_completed','blurred','inconsistent','missing_document','alternative_completed'].map(r=><option key={r}>{r}</option>)}</select></label>
 <label><input type="checkbox" checked={attested} onChange={e=>setAttested(e.target.checked)} />{t('I personally reviewed this evidence or completed the alternative review. No official registry claim.','Saya menyemak bukti ini sendiri atau melengkapkan semakan alternatif. Tiada dakwaan daftar rasmi.')}</label>
 <button disabled={busy||review.decision==='verified_manual'&&!attested} onClick={()=>void work(async()=>{await api('/identity/cases/'+review.row.id+'/review',{method:'POST',body:JSON.stringify({expected_version:review.row.version,decision:review.decision,reason_code:reason,attested})},csrf);setReview(null);})}>{t('Confirm identity decision','Sahkan keputusan identiti')}</button><button onClick={()=>setReview(null)}>{t('Cancel','Batal')}</button></section>}
 </section>;
}
