import {useEffect,useRef,useState} from 'react';
import {api} from './api';
type App={id:string;job_id:string;title:string;version:number;status:string;final_outcome:string;offer_accepted_at:string|null};
type Slot={id:string;job_id:string;interviewer_id:string;starts_at:string;ends_at:string;timezone:string;mode:string;location:string};
type Booking={id:string;application_id:string;revision:number;state:string;title:string;slot:Slot;scorecard_submitted:boolean};
type Context={applications:App[];slots:Slot[];bookings:Booking[];interviewers:{job_id:string;id:string;name:string}[];email_delivery:string};
const empty:Context={applications:[],slots:[],bookings:[],interviewers:[],email_delivery:'disabled'};
export function InterviewWorkspace({locale,csrf,staff,reload}:{locale:'en'|'ms';csrf:string;staff:boolean;reload:()=>Promise<void>}){
 const ms=locale==='ms';const [data,setData]=useState<Context>(empty),[scope,setScope]=useState(false),[app,setApp]=useState(''),[slot,setSlot]=useState(''),[person,setPerson]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[zone,setZone]=useState('Asia/Kuala_Lumpur'),[mode,setMode]=useState('online'),[location,setLocation]=useState(''),[reason,setReason]=useState(''),[notes,setNotes]=useState(''),[outcome,setOutcome]=useState('offer'),[attested,setAttested]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reminders,setReminders]=useState<{booking_id:string;starts_at:string}[]>([]);
 const dirty=useRef(false);const selected=data.applications.find(a=>a.id===app);
 async function refresh(){setData(await api<Context>('/interviews/context?staff_scope='+scope));setReminders(await api('/interviews/reminders'));}
 useEffect(()=>{let active=true;void api<Context>('/interviews/context?staff_scope='+scope).then(v=>{if(active)setData(v);}).catch(e=>{if(active)setError(String(e));});void api<{booking_id:string;starts_at:string}[]>('/interviews/reminders').then(v=>{if(active)setReminders(v);}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;};},[scope]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 async function work(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();dirty.current=false;await refresh();await reload();}catch(e){setError(String(e));}finally{setBusy(false);}}
 function when(s:Slot){try{return new Intl.DateTimeFormat(locale==='ms'?'ms-MY':'en-MY',{dateStyle:'medium',timeStyle:'short',timeZone:s.timezone}).format(new Date(s.starts_at))+' · '+s.timezone;}catch{return s.starts_at;}}
 return <section className="foundation-window" aria-label={ms?'Temu duga manusia':'Human interviews'}><header><strong>{ms?'Temu duga manusia':'Human interviews'}</strong></header><div className="foundation-content" onChange={()=>{dirty.current=true;}}>
 <p>{ms?'Senarai pendek bukan pengambilan. Temu duga, tawaran dan pengambilan akhir memerlukan tindakan manusia. Menerima tawaran tidak merekodkan pengambilan secara automatik.':'Shortlisted does not mean hired. Interviews, offers and final hiring require human action. Accepting an offer does not automatically record a hire.'}</p>
 {staff&&<label><input type="checkbox" checked={scope} onChange={e=>setScope(e.target.checked)}/>{ms?'Ruang staf / penemu duga':'Staff / interviewer workspace'}</label>}
 <button disabled={busy} onClick={()=>void work(refresh)}>{ms?'Muat semula temu duga':'Refresh interviews'}</button><p role="status">{error}</p>
 {reminders.map(r=><p key={r.booking_id} className="notice">{ms?'Peringatan temu duga disahkan dalam 24 jam':'Confirmed interview reminder within 24 hours'}: {r.starts_at}</p>)}
 <label>{ms?'Permohonan temu duga':'Interview application'}<select aria-label="Interview application" value={app} onChange={e=>{setApp(e.target.value);setSlot('');setPerson('');}}><option value="">{ms?'Pilih permohonan':'Select application'}</option>{data.applications.map(a=><option key={a.id} value={a.id}>{a.title} · {a.final_outcome}</option>)}</select></label>
 {selected&&<p>{ms?'Keputusan akhir manusia':'Human final outcome'}: {selected.final_outcome} {selected.offer_accepted_at&&(ms?'· tawaran diterima':'· offer accepted')}</p>}
 <label>{ms?'Slot tersedia':'Available slot'}<select aria-label="Available interview slot" value={slot} onChange={e=>setSlot(e.target.value)}><option value="">{ms?'Pilih slot':'Select slot'}</option>{data.slots.filter(s=>s.job_id===selected?.job_id).map(s=><option key={s.id} value={s.id}>{when(s)} · {s.mode}</option>)}</select></label>
 <label>{ms?'Sebab / mesej calon':'Reason / candidate message'}<textarea aria-label="Interview reason" maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label>
 {scope&&<><fieldset><legend>{ms?'Cipta slot dengan penemu duga ditugaskan':'Create slot with assigned interviewer'}</legend>
 <label>{ms?'Penemu duga':'Interviewer'}<select aria-label="Assigned interviewer" value={person} onChange={e=>setPerson(e.target.value)}><option value="">Select</option>{data.interviewers.filter(p=>p.job_id===selected?.job_id).map(p=><option key={p.id} value={p.id}>{p.name} · {p.id}</option>)}</select></label>
 <label>{ms?'Mula (UTC)':'Start (UTC)'}<input aria-label="Interview start UTC" type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>{ms?'Tamat (UTC)':'End (UTC)'}<input aria-label="Interview end UTC" type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label>
 <label>{ms?'Zon paparan IANA':'IANA display timezone'}<input aria-label="Interview timezone" value={zone} onChange={e=>setZone(e.target.value)}/></label>
 <label>{ms?'Kaedah':'Mode'}<select aria-label="Interview mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="online">Online</option><option value="physical">Physical</option></select></label><label>{ms?'Pautan HTTPS atau tempat fizikal':'HTTPS link or physical venue'}<input aria-label="Interview location" maxLength={500} value={location} onChange={e=>setLocation(e.target.value)}/></label>
 <button disabled={busy||!selected||!person||!start||!end||!location} onClick={()=>void work(async()=>{await api('/interviews/slots',{method:'POST',body:JSON.stringify({job_id:selected!.job_id,interviewer_id:person,starts_at:start+'Z',ends_at:end+'Z',timezone:zone,mode,location})},csrf);})}>{ms?'Cipta slot':'Create slot'}</button></fieldset>
 <button disabled={busy||!app||!slot||reason.trim().length<5} onClick={()=>void work(async()=>{await api('/interviews/proposals',{method:'POST',body:JSON.stringify({application_id:app,slot_id:slot,reason})},csrf);})}>{ms?'Cadangkan temu duga':'Propose interview'}</button></>}
 {!data.bookings.length&&<p>{ms?'Belum ada temu duga manusia.':'No human interviews yet.'}</p>}
 {data.bookings.map(b=><article key={b.id} className="application-card"><h3>{b.title}</h3><p>{when(b.slot)} · {b.state} · {ms?'Semakan':'Revision'} {b.revision}</p><p>{b.slot.mode}: {b.slot.location}</p>{b.slot.mode==='online'&&b.slot.location.startsWith('https://')&&<a href={b.slot.location} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{ms?'Sertai temu duga dalam talian':'Join online interview'}</a>}<a href={'/api/v1/interviews/bookings/'+b.id+'/calendar.ics'}>{ms?'Muat turun kalendar ICS':'Download calendar ICS'}</a>
 {['proposed','confirmed'].includes(b.state)&&<><button disabled={busy||scope||reason.trim().length<5} onClick={()=>void work(async()=>{await api('/interviews/bookings/'+b.id+'/changes',{method:'POST',body:JSON.stringify({expected_revision:b.revision,action:'confirm',reason})},csrf);})}>{ms?'Sahkan slot':'Confirm slot'}</button>
 <button disabled={busy||!slot||selected?.id!==b.application_id||reason.trim().length<5} onClick={()=>void work(async()=>{await api('/interviews/bookings/'+b.id+'/changes',{method:'POST',body:JSON.stringify({expected_revision:b.revision,action:'reschedule',slot_id:slot,reason})},csrf);})}>{ms?'Jadual semula':'Reschedule'}</button>
 <button disabled={busy||reason.trim().length<5} onClick={()=>void work(async()=>{await api('/interviews/bookings/'+b.id+'/changes',{method:'POST',body:JSON.stringify({expected_revision:b.revision,action:'cancel',reason})},csrf);})}>{ms?'Batalkan temu duga':'Cancel interview'}</button></>}
 {scope&&b.state==='confirmed'&&<><label>{ms?'Nota penemu duga peribadi':'Private interviewer notes'}<textarea aria-label={'Scorecard notes '+b.id} maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><p>{ms?'Rubrik manusia: kemahiran, komunikasi, penaakulan (0–5).':'Human rubric: skills, communication, reasoning (0–5).'}</p><Scorecard booking={b} notes={notes} busy={busy} csrf={csrf} work={work} ms={ms}/></>}
 {b.scorecard_submitted&&<p>{ms?'Kad skor manusia dihantar':'Human scorecard submitted'}</p>}
 </article>)}
 {scope&&data.slots.filter(s=>s.job_id===selected?.job_id).map(s=><button key={s.id} disabled={busy||reason.trim().length<5} onClick={()=>void work(async()=>{await api('/interviews/slots/'+s.id+'/cancel',{method:'POST',body:JSON.stringify({reason})},csrf);})}>{ms?'Batalkan slot':'Cancel available slot'} {when(s)}</button>)}
 {scope&&selected&&<fieldset><legend>{ms?'Keputusan akhir manusia':'Human final outcome'}</legend><select aria-label="Final outcome" value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="offer">Offer</option><option value="hired">Hired</option><option value="not_selected">Not selected</option></select><label><input type="checkbox" checked={attested} onChange={e=>setAttested(e.target.checked)}/>{ms?'Saya manusia yang menyemak bukti dan kad skor':'I am the human who reviewed evidence and the scorecard'}</label><button disabled={busy||!attested||reason.trim().length<15} onClick={()=>void work(async()=>{await api('/interviews/applications/'+selected.id+'/outcome',{method:'POST',body:JSON.stringify({expected_version:selected.version,outcome,reason,human_attested:attested})},csrf);})}>{ms?'Rekod keputusan akhir':'Record final outcome'}</button></fieldset>}
 {!scope&&selected?.final_outcome==='offer'&&!selected.offer_accepted_at&&<button disabled={busy} onClick={()=>void work(async()=>{await api('/interviews/applications/'+selected.id+'/accept-offer',{method:'POST',body:JSON.stringify({expected_version:selected.version})},csrf);})}>{ms?'Terima tawaran manusia':'Accept human offer'}</button>}
 <p>{ms?'Pemberitahuan dalam aplikasi sahaja. Penghantaran e-mel belum dikonfigurasi.':'In-app notices only. Email delivery is not configured.'}</p>
 </div></section>;
}
function Scorecard({booking,notes,busy,csrf,work,ms}:{ms:boolean;booking:Booking;notes:string;busy:boolean;csrf:string;work:(fn:()=>Promise<void>)=>Promise<void>}){
 const [skills,setSkills]=useState(3),[communication,setCommunication]=useState(3),[reasoning,setReasoning]=useState(3);
 return <fieldset><legend>{ms?'Kad skor penemu duga':'Interviewer scorecard'}</legend>{[['Skills',skills,setSkills],['Communication',communication,setCommunication],['Reasoning',reasoning,setReasoning]].map(([label,value,set])=><label key={String(label)}>{String(label)}<input aria-label={String(label)+' '+booking.id} type="number" min={0} max={5} step={1} value={Number(value)} onChange={e=>(set as (v:number)=>void)(Number(e.target.value))}/></label>)}<button disabled={busy||notes.trim().length<10} onClick={()=>void work(async()=>{await api('/interviews/bookings/'+booking.id+'/scorecard',{method:'POST',body:JSON.stringify({expected_revision:booking.revision,scores:{skills,communication,reasoning},notes})},csrf);})}>{ms?'Hantar kad skor manusia':'Submit human scorecard'}</button></fieldset>;
}
