import {useState} from 'react';
import {api} from './api';
export function PrivacyWorkspace({locale,csrf}:{locale:'en'|'ms';csrf:string}){
 const ms=locale==='ms';const [notice,setNotice]=useState<any>(null);const [requests,setRequests]=useState<any[]>([]);const [kind,setKind]=useState('access');const [reason,setReason]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function work(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 async function refresh(){setNotice(await api('/privacy/notice'));setRequests(await api<any[]>('/privacy/requests'));}
 return <section className="panel" aria-label={ms?'Pusat privasi':'Privacy centre'}><h2>{ms?'Pusat privasi':'Privacy centre'}</h2><p>{ms?'Demo sintetik sahaja. Gunakan data rekaan. Permintaan pemadaman memerlukan semakan manusia.':'Synthetic demo only. Use invented data. Erasure requests require human review.'}</p>
 <button disabled={busy} onClick={()=>void work(refresh)}>{ms?'Muat notis dan permintaan':'Load notice and requests'}</button>
 {notice&&<><p>{notice.text[locale]}</p><p>{ms?'Hubungan':'Contact'}: {notice.contact|| (ms?'Belum dikonfigurasi; pelepasan awam tertangguh.':'Not configured; public release deferred.')}</p></>}
 <p>{ms?'Eksport berskop dan berhalaman; nota sulit kakitangan, kunci soalan dan fail mentah dikecualikan. Mohon semakan akses tambahan.':'Exports are scoped and paginated; confidential staff notes, question keys and raw files are excluded. Request additional access review.'}</p>
 <div className="privacy-exports">{['profile','applications','events','consents','documents','practice','quiz','saved','tracking','chat','interviews','identity','background','requests','companies','manual_tracker','manual_history','resume_library','resume_links','analytics_observations','reminders','reminder_history','reminder_deliveries','reminder_preferences'].map(section=><a key={section} href={'/api/v1/privacy/export?section='+section}>{ms?'Eksport':'Export'} {section}</a>)}</div>
 <form onSubmit={e=>{e.preventDefault();void work(async()=>{await api('/privacy/requests',{method:'POST',body:JSON.stringify({kind,reason,idempotency_key:crypto.randomUUID()})},csrf);setReason('');await refresh();setMessage(ms?'Permintaan direkodkan untuk semakan; bukan pengesahan pemadaman.':'Request recorded for review; this does not confirm erasure.');});}}>
 <label>{ms?'Jenis permintaan':'Privacy request type'}<select aria-label="Privacy request type" value={kind} onChange={e=>setKind(e.target.value)}><option value="access">Access / Akses</option><option value="correction">Correction / Pembetulan</option><option value="erase_private_workspace">Erase private workspace / Padam ruang peribadi</option><option value="erase_account">Account erasure review / Semakan pemadaman akaun</option></select></label>
 <label>{ms?'Sebab permintaan':'Privacy request reason'}<textarea aria-label="Privacy request reason" minLength={10} maxLength={1000} required value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy}>{ms?'Hantar permintaan':'Submit privacy request'}</button></form><p role="status">{message}</p><ul>{requests.map(r=><li key={r.id}>{r.kind}: {r.state}</li>)}</ul></section>;
}
