import {useEffect,useState} from 'react';
import {api} from './api';
type Reminder={id:string;origin:string;reference_id:string|null;kind:string;title:string;due_at:string;timezone:string;state:string;revision:number;due:boolean;delivery:string};
type Context={now:string;policy:{enabled:boolean;mode:string};preference:{email_opt_in:boolean;revision:number};reminders:Reminder[];worker_configured:boolean;sender_configured:boolean};
export function ReminderWorkspace({locale,csrf}:{locale:'en'|'ms';csrf:string}){
 const ms=locale==='ms',t=(a:string,b:string)=>ms?b:a;
 const [data,setData]=useState<Context|null>(null),[rows,setRows]=useState<Reminder[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[more,setMore]=useState(false),[events,setEvents]=useState<any[]|null>(null),[preview,setPreview]=useState<any>(null);
 const [title,setTitle]=useState(''),[origin,setOrigin]=useState('personal'),[ref,setRef]=useState(''),[kind,setKind]=useState('personal'),[due,setDue]=useState(()=>new Date(Date.now()+86400000).toISOString()),[zone,setZone]=useState('Asia/Kuala_Lumpur'),[snooze,setSnooze]=useState(()=>new Date(Date.now()+86400000).toISOString());
 useEffect(()=>{if(!title)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[title]);
 async function refresh(){const c=await api<Context>('/reminders/context');setData(c);setRows(c.reminders);setMore(c.reminders.length===50);}
 async function work(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(String(e)+' '+t('Refresh to compare current revisions; nothing changes recruitment status.','Muat semula untuk banding versi semasa; tiada perubahan status pengambilan.'));}finally{setBusy(false);}}
 async function action(r:Reminder,value:string){await api('/reminders/edit',{method:'POST',body:JSON.stringify({id:r.id,expected_revision:r.revision,idempotency_key:crypto.randomUUID(),action:value,...(value==='snooze'?{due_at:snooze,timezone:r.timezone}:{})})},csrf);setEvents(null);await refresh();}
 function local(r:Reminder){try{return new Date(r.due_at).toLocaleString(ms?'ms-MY':'en-MY',{timeZone:r.timezone});}catch{return r.due_at;}}
 return <section className="panel" aria-label={t('Reminder workspace','Ruang peringatan')}><h2>{t('My reminders','Peringatan saya')}</h2><p>{t('Personal tasks and self-reported external interview preparation are separate from official human bookings. Follow-up reminders prompt you; no employer/contact is messaged.','Tugas peribadi dan persediaan temu duga luaran laporan kendiri berasingan daripada tempahan manusia rasmi. Peringatan susulan mengingatkan anda; tiada majikan/kenalan menerima mesej.')}</p><a href="/foundation?view=Interviews">{t('Confirmed interview notices and calendar','Notis temu duga disahkan dan kalendar')}</a><button disabled={busy} onClick={()=>void work(refresh)}>{t('Load reminders','Muat peringatan')}</button><p role="status">{message}</p>
 {data&&<><p>{t('Email delivery','Penghantaran e-mel')}: {data.policy.enabled&&data.worker_configured&&data.sender_configured?data.policy.mode:t('Disabled / worker unavailable','Dilumpuhkan / pekerja tidak tersedia')} · {t('Email preference','Pilihan e-mel')}: {data.preference.email_opt_in?t('Opted in','Dibenarkan'):t('Opted out','Tidak dibenarkan')}</p><p>{t('Email goes only to your verified account. No timely delivery is promised without an active worker. Opt-out cancels queued work; a message already dispatching may still arrive. Fixture receipts are synthetic; unknown means no automatic retry.','E-mel hanya ke akaun anda yang disahkan. Penghantaran tepat waktu tidak dijamin tanpa pekerja aktif. Penarikan izin membatalkan kerja beratur; mesej yang sedang dihantar mungkin masih tiba. Resit fixture ialah sintetik; status tidak diketahui tiada cubaan semula automatik.')}</p><button disabled={busy} onClick={()=>void work(async()=>{await api('/reminders/preference',{method:'POST',body:JSON.stringify({email_opt_in:!data.preference.email_opt_in,expected_revision:data.preference.revision,idempotency_key:crypto.randomUUID()})},csrf);await refresh();})}>{data.preference.email_opt_in?t('Unsubscribe reminder email','Henti langgan e-mel peringatan'):t('Opt in to account reminder email','Benarkan e-mel peringatan akaun')}</button></>}
 <button disabled={busy} onClick={()=>void work(async()=>setPreview(await api('/reminders/email-preview')))}>{t('Preview reminder email','Pratonton e-mel peringatan')}</button>{preview&&<section aria-label={t('Reminder email preview','Pratonton e-mel peringatan')}><h3>{preview.subject}</h3><p>{preview.body}</p><p>{preview.recipient} · {preview.delivery}</p></section>}
 <form onSubmit={e=>{e.preventDefault();void work(async()=>{await api('/reminders/edit',{method:'POST',body:JSON.stringify({action:'create',expected_revision:0,idempotency_key:crypto.randomUUID(),origin,reference_id:origin==='personal'?null:ref,kind,title,due_at:due,timezone:zone})},csrf);setTitle('');setRef('');await refresh();});}}>
 <label>{t('Reminder title','Tajuk peringatan')}<input aria-label="Reminder title" required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{t('Linked origin','Asal dipaut')}<select aria-label="Reminder origin" value={origin} onChange={e=>setOrigin(e.target.value)}>{['personal','internal','manual','discovery'].map(x=><option key={x}>{x}</option>)}</select></label>{origin!=='personal'&&<label>{t('Owned application/listing UUID','UUID permohonan/penyenaraian milik anda')}<input aria-label="Reminder reference" required value={ref} onChange={e=>setRef(e.target.value)}/></label>}
 <label>{t('Reminder type','Jenis peringatan')}<select aria-label="Reminder type" value={kind} onChange={e=>setKind(e.target.value)}>{['personal','follow_up','preparation'].map(x=><option key={x}>{x}</option>)}</select></label><label>{t('Due ISO time with offset (Z or +08:00)','Waktu ISO perlu dengan ofset (Z atau +08:00)')}<input aria-label="Reminder due time" required value={due} onChange={e=>setDue(e.target.value)}/></label><label>{t('Display IANA timezone','Zon waktu IANA paparan')}<input aria-label="Reminder timezone" required maxLength={80} value={zone} onChange={e=>setZone(e.target.value)}/></label><button disabled={busy}>{t('Create reminder','Cipta peringatan')}</button></form>
 <label>{t('New snooze ISO time with offset','Waktu ISO tangguh baharu dengan ofset')}<input aria-label="Snooze due time" value={snooze} onChange={e=>setSnooze(e.target.value)}/></label>
 <p>{t('Due/upcoming labels use the server time at last refresh. Explicit offsets disambiguate DST; timezone controls display. Follow-up/preparation cancels on closed outcomes; personal tasks remain until you act. Forget removes history/delivery metadata. Terminal records expire after the 90-day demo retention period when cleanup runs.','Label perlu/akan datang menggunakan waktu pelayan semasa muat semula. Ofset jelas membezakan DST; zon waktu mengawal paparan. Susulan/persediaan dibatalkan apabila hasil ditutup; tugas peribadi kekal sehingga anda bertindak. Padam membuang sejarah/metadata penghantaran. Rekod tamat luput selepas penyimpanan demo 90 hari apabila pembersihan dijalankan.')}</p>
 {data&&rows.length===0&&<p>{t('No reminders yet','Tiada peringatan lagi')}</p>}<ul>{rows.map(r=><li className="application-card" key={r.id}><h3>{r.title}</h3><p>{r.origin} · {r.kind} · {r.state} · {r.state==='active'?(r.due?t('Due','Perlu'):t('Upcoming','Akan datang')):''}</p><p>{local(r)} · {r.timezone} · UTC {r.due_at}</p><p>{t('Email occurrence','Kejadian e-mel')}: {r.delivery}</p>{r.state==='active'&&<>{['snooze','complete','cancel'].map(a=><button disabled={busy} key={a} onClick={()=>void work(()=>action(r,a))}>{({snooze:t('Snooze','Tangguh'),complete:t('Complete','Selesai'),cancel:t('Cancel','Batal')} as Record<string,string>)[a]} {r.title}</button>)}</>}<button disabled={busy} onClick={()=>void work(async()=>setEvents(await api<any[]>('/reminders/history/'+r.id)))}>{t('History','Sejarah')} {r.title}</button><button disabled={busy} onClick={()=>void work(()=>action(r,'forget'))}>{t('Forget reminder','Padam peringatan')} {r.title}</button></li>)}</ul>
 {more&&<button disabled={busy} onClick={()=>void work(async()=>{const next=await api<Context>('/reminders/context?offset='+rows.length);setRows(prev=>[...prev,...next.reminders]);setMore(next.reminders.length===50);})}>{t('Load more reminders','Muat lagi peringatan')}</button>}
 {events&&<section aria-label={t('Reminder history','Sejarah peringatan')}><h3>{t('History','Sejarah')}</h3><ol>{events.map((e,i)=><li key={i}>{e.event} · {e.revision} · {e.due_at} · {e.created_at}</li>)}</ol></section>}
 </section>;
}
