import {useEffect,useRef,useState} from 'react';
import type {AgentResult} from './RecruiterWorkspace';

export type FairControls={neutralize:boolean;anonymous:boolean;comparison:boolean;weight:number};
export const defaultFairControls:FairControls={neutralize:true,anonymous:true,comparison:false,weight:30};
export type TalentRow={id:string;job_id:string;name:string;stage:string;status:string;version?:number;screening_completed?:boolean;final_outcome?:string;result?:AgentResult|null};
export type TalentJob={id:string;title:string;published?:boolean;active?:boolean};
const score=(r:TalentRow,key:string)=>r.result?.fit.scores[key];
export function FairHiringControls({value,onChange}:{value:FairControls;onChange:(next:FairControls)=>void}){
 return <section className="fair-controls surface-card" aria-label="Fair Hiring Controls"><h2>Fair Hiring Controls</h2><p>Choose what reviewers see. Controls apply to the current review session.</p>
 <label className="fair-control-row"><span><strong>Hide school and company names</strong><small>Replace institutional names with neutral background categories.</small></span><input type="checkbox" checked={value.neutralize} onChange={e=>onChange({...value,neutralize:e.target.checked})}/></label>
 <label className="fair-control-row"><span><strong>Hide candidate identity</strong><small>Use candidate IDs during early-stage review.</small></span><input type="checkbox" checked={value.anonymous} onChange={e=>onChange({...value,anonymous:e.target.checked})}/></label>
 <label>Scoring view<select aria-label="Scoring view" value={value.comparison?'comparison':'merit'} onChange={e=>onChange({...value,comparison:e.target.value==='comparison'})}><option value="merit">Focus on skills only</option><option value="comparison">Compare reputation influence — audit only</option></select></label>
 {value.comparison&&<label>Reputation comparison weight: {value.weight}%<input aria-label={"Reputation comparison weight: "+value.weight+"%"} type="range" min={0} max={50} step={1} value={value.weight} onChange={e=>onChange({...value,weight:Number(e.target.value)})}/></label>}
 <p className="review-caption">Hiring recommendations always use blind merit. Reputation comparison is an audit simulation; it cannot change stages or decisions.</p></section>
}
function displayName(row:TalentRow,controls:FairControls){return controls.anonymous?'Candidate #'+row.id.slice(-6):row.name||'Candidate'}
export function TalentDashboard({jobs,rows,controls,onControls,onReview,onDecision,busy,view='overview'}:{jobs:TalentJob[];rows:TalentRow[];controls:FairControls;onControls:(v:FairControls)=>void;onReview:(row:TalentRow)=>void;onDecision?:(row:TalentRow,action:'shortlist'|'reject'|'note',reason:string)=>void;busy?:boolean;view?:'overview'|'candidates'|'fairness'}){
 const [job,setJob]=useState('all'),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[sort,setSort]=useState('match'),[minFit,setMinFit]=useState(0),[minTrajectory,setMinTrajectory]=useState(0),[potential,setPotential]=useState(false),[selected,setSelected]=useState<string|null>(null),[detailTab,setDetailTab]=useState('Scores'),[reason,setReason]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 const selectedRow=rows.find(r=>r.id===selected);
 useEffect(()=>{if(selectedRow&&!dialog.current?.open)dialog.current?.showModal();else if(!selectedRow&&dialog.current?.open)dialog.current?.close();},[selectedRow]);
 const scoped=rows.filter(r=>(job==='all'||r.job_id===job)&&(status==='all'||r.status===status)&&displayName(r,controls).toLowerCase().includes(search.toLowerCase())&&(!minFit||(score(r,'overall_position_fit')??-1)>=minFit)&&(!minTrajectory||(score(r,'trajectory_slope')??-1)>=minTrajectory)&&(!potential||r.result?.fit.resume_context_intelligence?.high_potential_candidate));
 const visible=[...scoped].sort((a,b)=>{if(sort==='name')return displayName(a,controls).localeCompare(displayName(b,controls));const key=sort==='trajectory'?'trajectory_slope':'overall_position_fit';const av=score(a,key),bv=score(b,key);if(av==null)return bv==null?0:1;if(bv==null)return -1;return sort==='match-asc'?av-bv:bv-av;});
 const scored=scoped.filter(r=>score(r,'overall_position_fit')!=null),mean=scored.length?Math.round(scored.reduce((s,r)=>s+score(r,'overall_position_fit')!,0)/scored.length):null;
 const states=[['Applied',['applied']],['Under review',['under_review','paused']],['Shortlisted',['shortlisted']],['Hired',['hired']],['Closed',['rejected','withdrawn','job_closed']]] as const;
 function open(r:TalentRow){setSelected(r.id);setDetailTab('Scores');setReason('')}
 const compared=scored.map(r=>{const merit=score(r,'overall_position_fit')!,reputation=r.result?.fit.bias_control?.prestige_score??0;return {r,merit,comparison:Math.round(merit*(100-controls.weight)/100+reputation*controls.weight/100)}});
 return <div className="talent-dashboard"><div className="section-heading"><div><h2>{view==='overview'?'Pipeline Overview':view==='fairness'?'Fair hiring review':'Candidates'}</h2><p className="review-caption">{job==='all'?'All loaded positions':jobs.find(j=>j.id===job)?.title} · {scoped.length} loaded applications · {scored.length} assessed</p></div><label>Position<select aria-label="Position" value={job} onChange={e=>setJob(e.target.value)}><option value="all">All positions</option>{jobs.map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></label></div>
 {view==='overview'&&<>
 <div className="metric-grid overview-kpis">{[['Active Positions',jobs.filter(j=>(job==='all'||j.id===job)&&(j.active||j.published)).length],['Active Pipeline',scoped.filter(r=>!['hired','rejected','withdrawn','job_closed'].includes(r.status)).length],['Screening Completed',scoped.filter(r=>r.screening_completed).length],['Hired',scoped.filter(r=>r.status==='hired'||r.final_outcome==='hired').length],['Average Position Fit',mean==null?'—':mean+'%']].map(([label,value])=><div className="metric" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
 <section className="surface-card trajectory-panel"><h3>Trajectory Analysis</h3><p>Position fit versus career progression and learning signals. Select a point for the candidate profile.</p><div className="trajectory-chart" aria-label="Position fit versus trajectory chart"><span className="chart-axis-y">Trajectory score / 100</span><div className="scatter-area"><span className="quadrant-label">High fit + high trajectory</span>{scored.filter(r=>score(r,'trajectory_slope')!=null).map(r=><button className="scatter-point" key={r.id} style={{left:score(r,'overall_position_fit')+'%',bottom:score(r,'trajectory_slope')+'%'}} aria-label={displayName(r,controls)+': position fit '+score(r,'overall_position_fit')+', trajectory '+score(r,'trajectory_slope')} title={displayName(r,controls)} onClick={()=>open(r)} />)}</div><span className="chart-axis-x">Position fit / 100 · 0 → 100</span></div>{!scored.length&&<p>No assessed resumes yet. Run a candidate review to populate the chart.</p>}</section></>}
 {view!=='candidates'&&<><FairHiringControls value={controls} onChange={onControls}/><section className="surface-card comparison-panel"><h3>Fairness comparison</h3><p>Same role evidence, different institution reputation. This descriptive comparison does not measure legal fairness.</p>{controls.comparison&&compared.length?<table><caption>Audit simulation · no hiring score changes</caption><thead><tr><th>Candidate</th><th>Merit</th><th>Comparison</th><th>Change</th></tr></thead><tbody>{compared.map(({r,merit,comparison})=><tr key={r.id}><td>{displayName(r,controls)}</td><td>{merit}</td><td>{comparison}</td><td>{comparison-merit>0?'+':''}{comparison-merit}</td></tr>)}</tbody></table>:<p>{controls.comparison?'Review resumes to compare real calculated scores.':'Merit scoring active · Reputation contributes 0% to recommendations.'}</p>}</section></>}
 {view==='overview'&&<section className="surface-card positions-panel"><h3>Position Dashboards</h3><div className="position-grid">{jobs.map(j=><button key={j.id} aria-pressed={job===j.id} onClick={()=>setJob(job===j.id?'all':j.id)}><strong>{j.title}</strong><small>{rows.filter(r=>r.job_id===j.id).length} applications · {j.active||j.published?'Open':'Draft / closed'}</small></button>)}</div></section>}
 <section className="surface-card pipeline-panel"><div className="section-heading"><h3>Candidate Pipelines</h3><span>{visible.length} visible applications</span></div><div className="candidate-filters"><label>Search candidates<input value={search} maxLength={120} onChange={e=>setSearch(e.target.value)}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{Array.from(new Set(rows.map(r=>r.status))).map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label><label>Sort candidates<select aria-label="Sort candidates" value={sort} onChange={e=>setSort(e.target.value)}><option value="match">Highest Position Fit</option><option value="match-asc">Lowest Position Fit</option><option value="trajectory">Highest Trajectory</option><option value="name">Candidate name / ID</option></select></label><label>Minimum position fit<input type="number" min={0} max={100} value={minFit} onChange={e=>setMinFit(Math.min(100,Math.max(0,Number(e.target.value))))}/></label><label>Minimum trajectory<input type="number" min={0} max={100} value={minTrajectory} onChange={e=>setMinTrajectory(Math.min(100,Math.max(0,Number(e.target.value))))}/></label><label><input type="checkbox" checked={potential} onChange={e=>setPotential(e.target.checked)}/>High-potential signals only</label></div>
 <div className="pipeline-columns" role="region" aria-label="Candidate pipeline stages" tabIndex={0}>{states.map(([title,statuses])=><section key={title}><h4>{title} <span>{visible.filter(r=>(statuses as readonly string[]).includes(r.status)).length}</span></h4>{visible.filter(r=>(statuses as readonly string[]).includes(r.status)).map(r=><article className="talent-card" key={r.id}><strong>{displayName(r,controls)}</strong><p>{jobs.find(j=>j.id===r.job_id)?.title} · {r.stage}</p><div className="talent-scores"><span>Position Fit<strong>{score(r,'overall_position_fit')==null?'Not assessed':score(r,'overall_position_fit')+'%'}</strong></span><span>Trajectory score<strong>{score(r,'trajectory_slope')==null?'Not assessed':score(r,'trajectory_slope')+'/100'}</strong></span></div>{r.result?.fit.resume_context_intelligence?.high_potential_candidate&&<p className="talent-alert">High-potential signals</p>}{r.result?.fit.resume_context_intelligence?.undervalued_talent_alert&&<p className="talent-alert">Merit exceeds pedigree signals</p>}<button onClick={()=>open(r)}>View candidate</button><button disabled={busy} onClick={()=>onReview(r)}>Review resume</button></article>)}</section>)}</div>{!visible.length&&<p>No applications match these filters.</p>}</section>
 <dialog ref={dialog} className="talent-dialog" onCancel={()=>setSelected(null)} onClose={()=>setSelected(null)} aria-label="Candidate profile">{selectedRow&&<><header><strong>{displayName(selectedRow,controls)} — Candidate profile</strong><button autoFocus onClick={()=>setSelected(null)}>Close</button></header><div className="dialog-content"><p>{jobs.find(j=>j.id===selectedRow.job_id)?.title} · {selectedRow.stage} · {selectedRow.status.replaceAll('_',' ')}</p><nav aria-label="Candidate detail tabs">{['Scores','Trajectory','Interview','Report'].map(v=><button aria-pressed={detailTab===v} key={v} onClick={()=>setDetailTab(v)}>{v}</button>)}</nav>{selectedRow.result?<>{detailTab==='Scores'&&<><h3>Score breakdown</h3><p>{selectedRow.result.fit.score_explanation}</p>{selectedRow.result.fit.score_contributors?.map((v,i)=><div className="contributor" key={i}><strong>{v.factor}</strong><span>{v.score}/100 · {v.weight}% weight</span><p>{v.reason}</p></div>)}<h4>Advocate signals</h4><ul>{selectedRow.result.fit.debate?.advocate_pros?.map(s=><li key={s}>{s}</li>)}</ul><h4>Recruiter concerns</h4><ul>{selectedRow.result.fit.debate?.critical_recruiter_cons?.map(s=><li key={s}>{s}</li>)}</ul></>}{detailTab==='Trajectory'&&<><h3>Trajectory score: {score(selectedRow,'trajectory_slope')}/100</h3><p>This is the original deterministic career-growth heuristic, not a prediction of future performance.</p><p>It considers progression in role titles, growth terms, skills breadth and awards. It starts at 62, adds bounded evidence bonuses and caps at 98. A missing resume receives no dashboard score.</p><p>Trajectory contributes 15% of the merit formula.</p></>}{detailTab==='Interview'&&<><h3>Screening questions & feedback</h3><ol>{selectedRow.result.questions.map(q=><li key={q}>{q}</li>)}</ol>{selectedRow.result.evaluation?<pre>{JSON.stringify(selectedRow.result.evaluation,null,2)}</pre>:<p>No answer evaluation available. Preview questions do not replace the published quiz.</p>}</>}{detailTab==='Report'&&<><h3>Recommendation & learning roadmap</h3><p>{selectedRow.result.report.sourcing_pitch}</p><ol>{Object.values(selectedRow.result.report.upskilling_roadmap).map(s=><li key={s}>{s}</li>)}</ol><details><summary>Invitation draft</summary><pre>{selectedRow.result.report.outreach_email}</pre></details></>}</>:<p>No assessment yet. Review the authorized resume to generate evidence-based recommendations.</p>}<p className="review-caption">Read-only recommendation · Human decisions use the guarded application workflow.</p></div></>}</dialog>
 </div>
}
