import {useEffect,useRef,useState} from 'react';
import {api} from './api';
type Company={id:string;name:string;domain:string;note:string;revision:number;employer_id:string|null};
type Resume={id:string;label:string;state:string;expires_at:string;created_at:string;deleted_at:string|null;application_copies:number};
type Row={id:string;origin:string;title:string;company:string;company_id:string;status:string;stage:string|null;url:string;note:string;applied_on:string|null;archived:boolean;revision:number;resume_version_id:string|null};
type App={id:string;version:number;stage:string;status:string};
export function TrackerWorkspace({locale,csrf,applications,reload}:{locale:'en'|'ms';csrf:string;applications:App[];reload:()=>Promise<void>}){
 const ms=locale==='ms';const text=(a:string,b:string)=>ms?b:a;
 const [rows,setRows]=useState<Row[]>([]),[companies,setCompanies]=useState<Company[]>([]),[resumes,setResumes]=useState<Resume[]>([]),[links,setLinks]=useState<any[]>([]),[history,setHistory]=useState<any[]|null>(null);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[loaded,setLoaded]=useState(false),[dirty,setDirty]=useState(false),[more,setMore]=useState(false);
 const [companyMore,setCompanyMore]=useState(false),[resumeMore,setResumeMore]=useState(false);
 const [query,setQuery]=useState(''),[origin,setOrigin]=useState('all'),[status,setStatus]=useState(''),[companyFilter,setCompanyFilter]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[archived,setArchived]=useState(false);
 const [company,setCompany]=useState<Company|null>(null),[name,setName]=useState(''),[domain,setDomain]=useState(''),[companyNote,setCompanyNote]=useState('');
 const [manual,setManual]=useState<Row|null>(null),[companyId,setCompanyId]=useState(''),[title,setTitle]=useState(''),[url,setUrl]=useState(''),[manualStatus,setManualStatus]=useState('considering'),[applied,setApplied]=useState(''),[note,setNote]=useState(''),[resumeId,setResumeId]=useState(''),[manualArchived,setManualArchived]=useState(false);
 const [label,setLabel]=useState(''),[file,setFile]=useState<File|null>(null),[copyResume,setCopyResume]=useState(''),[applicationId,setApplicationId]=useState(''),[privateUrl,setPrivateUrl]=useState('');
 useEffect(()=>{if(!dirty&&!name&&!title&&!label&&!file)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,name,title,label,file]);
 function search(offset=0){return '/tracker/list?'+new URLSearchParams({q:query,origin,status,company:companyFilter,archived:String(archived),offset:String(offset),...(from?{from_date:from}:{}),...(to?{to_date:to}:{})});}
 async function refresh(){const [r,c,v,l]=await Promise.all([api<Row[]>(search()),api<Company[]>('/tracker/companies'),api<Resume[]>('/tracker/resumes'),api<any[]>('/tracker/resume-links')]);setRows(r);setMore(r.length===50);setCompanies(c);setCompanyMore(c.length===50);setResumes(v);setResumeMore(v.length===50);setLinks(l);setLoaded(true);}
 async function work(fn:()=>Promise<void>){setBusy(true);setMessage('');setPrivateUrl('');try{await fn();}catch(e){setMessage(String(e)+' '+text('For duplicate URLs or stale revisions, refresh and compare/edit the existing record; nothing is merged automatically.','Untuk URL pendua atau versi lama, muat semula dan banding/sunting rekod sedia ada; tiada gabungan automatik.'));}finally{setBusy(false);}}
 function editCompany(c:Company|null){if((name||companyNote)&&!window.confirm(text('Replace unsaved company form?','Ganti borang syarikat belum disimpan?')))return;setCompany(c);setName(c?.name||'');setDomain(c?.domain||'');setCompanyNote(c?.note||'');setDirty(true);}
 function editManual(r:Row|null){if((title||note||url)&&!window.confirm(text('Replace unsaved external form?','Ganti borang luaran belum disimpan?')))return;setManual(r);setCompanyId(r?.company_id||'');setTitle(r?.title||'');setUrl(r?.url||'');setManualStatus(r?.status||'considering');setApplied(r?.applied_on||'');setNote(r?.note||'');setResumeId(r?.resume_version_id||'');setManualArchived(r?.archived||false);setDirty(true);}
 const fileInput=useRef<HTMLInputElement>(null);
 const usable=resumes.filter(v=>v.state==='ready'&&!v.deleted_at&&new Date(v.expires_at)>new Date());
 return <section className="panel" aria-label={text('Tracker workspace','Ruang penjejak')}><h2>{text('Tracker, companies and resume versions','Penjejak, syarikat dan versi resume')}</h2>
 <p>{text('Internal progress is confirmed by KerjaOS. External records are self-reported; visiting a source is not an application. Company notes and library resumes are private.','Kemajuan dalaman disahkan oleh KerjaOS. Rekod luaran ialah laporan kendiri; melawat sumber bukan permohonan. Nota syarikat dan pustaka resume adalah peribadi.')}</p>
 <button disabled={busy} onClick={()=>void work(refresh)}>{text('Load tracker','Muat penjejak')}</button><p role="status">{message}</p>
 <form onSubmit={e=>{e.preventDefault();void work(refresh);}}><label>{text('Search tracker','Cari penjejak')}<input aria-label="Search tracker" maxLength={120} value={query} onChange={e=>setQuery(e.target.value)}/></label>
 <label>{text('Record origin','Asal rekod')}<select aria-label="Record origin" value={origin} onChange={e=>setOrigin(e.target.value)}>{['all','internal','manual','discovery'].map(x=><option key={x}>{x}</option>)}</select></label>
 <label>{text('Tracker status','Status penjejak')}<select aria-label="Tracker status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">{text('All statuses','Semua status')}</option>{['considering','saved','applied','under_review','on_hold','shortlisted','interview_ready','interview','offer','hired','rejected','withdrawn','job_closed'].map(x=><option key={x}>{x}</option>)}</select></label>
 <label>{text('Company filter','Tapis syarikat')}<input aria-label="Company filter" maxLength={120} value={companyFilter} onChange={e=>setCompanyFilter(e.target.value)}/></label><label>{text('Applied from','Mohon dari')}<input aria-label="Applied from" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{text('Applied until','Mohon sehingga')}<input aria-label="Applied until" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>{text('Include archived records','Sertakan rekod arkib')}</label><button disabled={busy}>{text('Filter tracker','Tapis penjejak')}</button></form>
 {loaded&&rows.length===0&&<p>{text('No records match. Unknown applied dates are excluded by date filters.','Tiada rekod sepadan. Tarikh permohonan tidak diketahui dikecualikan oleh penapis tarikh.')}</p>}
 <ul>{rows.map(r=><li className="application-card" key={r.origin+r.id}><h3>{r.title}</h3><p>{r.company} · {r.origin} · {r.stage||text('Self-reported','Laporan kendiri')} · {r.status}{r.archived?' · archived':''}</p><p>{text('Applied date','Tarikh mohon')}: {r.applied_on||text('Unknown','Tidak diketahui')}</p><p>{r.note}</p>{r.url&&<a href={r.url} rel="noopener noreferrer" target="_blank">{text('Open external source','Buka sumber luaran')}</a>} <button disabled={busy} onClick={()=>void work(async()=>setHistory(await api<any[]>('/tracker/history/'+r.origin+'/'+r.id)))}>{text('Record history','Sejarah rekod')}</button>
 {r.origin==='internal'&&<a href={'/foundation?application='+r.id}>{text('Open internal application','Buka permohonan dalaman')}</a>}
 {r.origin==='manual'&&<><button disabled={busy} onClick={()=>editManual(r)}>{text('Edit external record','Sunting rekod luaran')}</button><button disabled={busy} onClick={()=>void work(async()=>{await api('/tracker/forget',{method:'POST',body:JSON.stringify({kind:'manual',id:r.id,expected_revision:r.revision})},csrf);await refresh();})}>{text('Forget external record','Padam rekod luaran')}</button></>}
 {r.origin==='discovery'&&<p>{text('Edit/forget this source-linked record in Discover.','Sunting/padam rekod bersumber ini dalam Temui.')}</p>}</li>)}</ul>
 {more&&<button disabled={busy} onClick={()=>void work(async()=>{const next=await api<Row[]>(search(rows.length));setRows(prev=>[...prev,...next]);setMore(next.length===50);})}>{text('Load more tracker records','Muat lagi rekod penjejak')}</button>}
 {history&&<section aria-label={text('Tracker record history','Sejarah rekod penjejak')}><h3>{text('History','Sejarah')}</h3><ol>{history.map((h,i)=><li key={h.id||i}>{h.created_at} · {h.status}<p>{h.reason}</p>{h.snapshot?.resume_version_id&&<p>{text('Recorded resume version','Versi resume direkod')}: {h.snapshot.resume_version_id}</p>}</li>)}</ol></section>}
 <h3>{text('Private companies','Syarikat peribadi')}</h3><ul>{companies.map(c=><li key={c.id}><strong>{c.name}</strong> · {c.domain}<p>{c.note}</p><button onClick={()=>editCompany(c)}>{text('Edit company','Sunting syarikat')} {c.name}</button><button disabled={busy} onClick={()=>void work(async()=>{await api('/tracker/forget',{method:'POST',body:JSON.stringify({kind:'company',id:c.id,expected_revision:c.revision})},csrf);await refresh();})}>{text('Forget company','Padam syarikat')} {c.name}</button></li>)}</ul>{companyMore&&<button disabled={busy} onClick={()=>void work(async()=>{const c=await api<Company[]>('/tracker/companies?offset='+companies.length);setCompanies(v=>[...v,...c]);setCompanyMore(c.length===50);})}>{text('Load more companies','Muat lagi syarikat')}</button>}<button onClick={()=>editCompany(null)}>{text('New company','Syarikat baharu')}</button>
 <form onSubmit={e=>{e.preventDefault();void work(async()=>{await api('/tracker/companies',{method:'POST',body:JSON.stringify({id:company?.id||null,expected_revision:company?.revision||0,name,domain,note:companyNote,employer_id:company?.employer_id||null})},csrf);setCompany(null);setName('');setDomain('');setCompanyNote('');setDirty(false);await refresh();});}}>
 <label>{text('Company name','Nama syarikat')}<input aria-label="Company name" required maxLength={120} value={name} onChange={e=>{setName(e.target.value);setDirty(true);}}/></label><label>{text('Company domain','Domain syarikat')}<input aria-label="Company domain" maxLength={253} value={domain} onChange={e=>{setDomain(e.target.value);setDirty(true);}}/></label><label>{text('Private company note','Nota syarikat peribadi')}<textarea aria-label="Private company note" maxLength={1000} value={companyNote} onChange={e=>{setCompanyNote(e.target.value);setDirty(true);}}/></label><button disabled={busy}>{text('Save company','Simpan syarikat')}</button></form>
 <h3>{text('Manual external application','Permohonan luaran manual')}</h3><button onClick={()=>editManual(null)}>{text('New external record','Rekod luaran baharu')}</button>
 <form onSubmit={e=>{e.preventDefault();void work(async()=>{await api('/tracker/manual',{method:'POST',body:JSON.stringify({id:manual?.id||null,expected_revision:manual?.revision||0,company_id:companyId,title,url,status:manualStatus,applied_on:applied||null,note,resume_version_id:resumeId||null,archived:manualArchived})},csrf);setManual(null);setTitle('');setUrl('');setNote('');setApplied('');setResumeId('');setManualArchived(false);setDirty(false);await refresh();});}} onChange={()=>setDirty(true)}>
 <label>{text('Record company','Syarikat rekod')}<select aria-label="Record company" required value={companyId} onChange={e=>setCompanyId(e.target.value)}><option value="">—</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>{text('External role title','Tajuk jawatan luaran')}<input aria-label="External role title" required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{text('External job URL','URL jawatan luaran')}<input aria-label="External job URL" type="url" maxLength={2000} value={url} onChange={e=>setUrl(e.target.value)}/></label><label>{text('Self-reported status','Status laporan kendiri')}<select aria-label="Self-reported status" value={manualStatus} onChange={e=>setManualStatus(e.target.value)}>{['considering','applied','interview','offer','rejected','withdrawn','hired'].map(x=><option key={x}>{x}</option>)}</select></label><label>{text('Known applied date','Tarikh mohon diketahui')}<input aria-label="Known applied date" type="date" value={applied} onChange={e=>setApplied(e.target.value)}/></label><label>{text('External record note','Nota rekod luaran')}<textarea aria-label="External record note" maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><label>{text('Submitted resume version','Versi resume dihantar')}<select aria-label="Submitted resume version" value={resumeId} onChange={e=>setResumeId(e.target.value)}><option value="">{text('Not recorded','Tidak direkod')}</option>{resumes.map(v=><option key={v.id} value={v.id} disabled={!usable.includes(v)&&v.id!==manual?.resume_version_id}>{v.label} · {v.id} · {v.state}</option>)}</select></label><label><input type="checkbox" checked={manualArchived} onChange={e=>setManualArchived(e.target.checked)}/>{text('Archive external record','Arkib rekod luaran')}</label><button disabled={busy}>{text('Save external record','Simpan rekod luaran')}</button></form>
 <h3>{text('Private resume library','Pustaka resume peribadi')}</h3><p>{text('Immutable PDF versions expire after 90 days. Removing a library copy revokes access and queues object cleanup; application copies remain for separate retention review. Selection does not reuse identity or credit consent.','Versi PDF kekal tamat selepas 90 hari. Pembuangan salinan pustaka membatalkan akses dan menjadualkan pembersihan objek; salinan permohonan kekal untuk semakan penyimpanan berasingan. Pemilihan tidak menggunakan semula persetujuan identiti atau kredit.')}</p>
 <form onSubmit={e=>{e.preventDefault();if(!file)return;void work(async()=>{const body=new FormData();body.append('label',label);body.append('file',file);await api('/tracker/resumes/upload',{method:'POST',body},csrf);setLabel('');setFile(null);if(fileInput.current)fileInput.current.value='';setDirty(false);await refresh();});}}><label>{text('Resume version label','Label versi resume')}<input aria-label="Resume version label" required maxLength={120} value={label} onChange={e=>{setLabel(e.target.value);setDirty(true);}}/></label><label>{text('Library PDF','PDF pustaka')}<input ref={fileInput} aria-label="Library PDF" type="file" accept="application/pdf" required onChange={e=>{setFile(e.target.files?.[0]||null);setDirty(true);}}/></label><button disabled={busy}>{text('Upload resume version','Muat naik versi resume')}</button></form>
 <ul>{resumes.map(v=><li key={v.id}>{v.label} · {v.state} · {v.created_at??''} · {v.expires_at} · {v.application_copies} {text('application copies','salinan permohonan')}{usable.includes(v)&&<button disabled={busy} onClick={()=>void work(async()=>{const r=await api<{url:string}>('/tracker/resumes/'+v.id+'/access',{method:'POST'},csrf);setPrivateUrl(r.url);})}>{text('Preview resume','Pratonton resume')} {v.label}</button>}{!v.deleted_at&&<button disabled={busy} onClick={()=>void work(async()=>{await api('/tracker/resumes/'+v.id+'/retire',{method:'POST'},csrf);await refresh();setMessage(text('Library access revoked; cleanup pending. Application copies retained.','Akses pustaka dibatalkan; pembersihan tertangguh. Salinan permohonan dikekalkan.'));})}>{text('Remove library version','Buang versi pustaka')} {v.label}</button>}</li>)}</ul>{resumeMore&&<button disabled={busy} onClick={()=>void work(async()=>{const v=await api<Resume[]>('/tracker/resumes?offset='+resumes.length);setResumes(prev=>[...prev,...v]);setResumeMore(v.length===50);})}>{text('Load more resume versions','Muat lagi versi resume')}</button>}{privateUrl&&<a href={privateUrl} target="_blank" rel="noreferrer">{text('Private PDF · 60 seconds','PDF peribadi · 60 saat')}</a>}
 <form onSubmit={e=>{e.preventDefault();const app=applications.find(a=>a.id===applicationId);if(!app)return;void work(async()=>{await api('/tracker/resumes/'+copyResume+'/clone',{method:'POST',body:JSON.stringify({application_id:app.id,expected_version:app.version,idempotency_key:crypto.randomUUID()})},csrf);await reload();await refresh();setMessage(text('Application copy created. Human screening fixes its submission snapshot.','Salinan permohonan dicipta. Saringan manusia menetapkan snapshot penyerahan.'));});}}><label>{text('Copy resume version','Salin versi resume')}<select aria-label="Copy resume version" required value={copyResume} onChange={e=>setCopyResume(e.target.value)}><option value="">—</option>{usable.map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select></label><label>{text('Copy to application','Salin ke permohonan')}<select aria-label="Copy to application" required value={applicationId} onChange={e=>setApplicationId(e.target.value)}><option value="">—</option>{applications.filter(a=>['P0','P1'].includes(a.stage)&&!['withdrawn','rejected','hired','job_closed'].includes(a.status)).map(a=><option key={a.id} value={a.id}>{a.id} · {a.stage}</option>)}</select></label><button disabled={busy}>{text('Create application resume copy','Cipta salinan resume permohonan')}</button></form>
 <h3>{text('Resume submission links','Pautan penyerahan resume')}</h3><ul>{links.map(l=><li key={l.document_id}>{l.application_id} · {l.version_id} · {l.submitted_snapshot?text('Frozen submitted snapshot','Snapshot penyerahan tetap'):text('Copy created; check screening state','Salinan dicipta; semak keadaan saringan')}</li>)}</ul>
 </section>;
}
