import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('candidate and MFA staff analytics preserve scoped provenance, filters, exports and accessible empty charts',async({browser})=>{
 // Three isolated sessions + axe; cold local Vite navigation can consume ~29s. No retries.
 test.setTimeout(60000);
 async function start(email:string){const context=await browser.newContext(),page=await context.newPage();let logged=false;const staff=email.startsWith('hm');await page.route('**/api/v1/**',async route=>{const u=new URL(route.request().url()),p=u.pathname;let data:any=[],status=200;
 if(p.endsWith('/auth/login')){logged=true;data={};}else if(p.endsWith('/me')){status=logged?200:401;data=logged?{id:email,email,aal:staff?'aal2':'aal1',csrf_token:'fixture',memberships:staff?[{role:'hm',employer_id:'e'}]:[],password_recovery:false}:{detail:'Sign in required'};}
 else if(p.endsWith('/applications')||p.endsWith('/jobs'))data=[];
 else if(p.includes('/interviews/'))data=p.endsWith('/context')?{applications:[],slots:[],bookings:[],interviewers:[],email_delivery:'disabled'}:[];
 else if(p.includes('/identity/'))data=p.endsWith('/policy')?{version:'fixture',text:{en:'Synthetic',ms:'Sintetik'},real_capture_enabled:false}:[];
 else if(p.includes('/background/'))data=p.endsWith('/policy')?{checks:[]}:[];
 else if(p.includes('/discover/'))data=p.endsWith('/progress')?{enabled:false,sources:[]}:[];
 else if(p.endsWith('/analytics/report')){const scope=u.searchParams.get('scope');expect(scope==='staff'?staff:true).toBe(true);expect(u.searchParams.get('timezone')).toBe('Asia/Kuala_Lumpur');const empty=u.searchParams.get('company')==='absent',internal=staff?2:email.startsWith('a')?2:1;data={scope,from_date:'2026-01-01',to_date:'2026-12-31',timezone:'Asia/Kuala_Lumpur',generated_at:'Synthetic snapshot',total:empty?0:internal+(staff?0:1),unknown_dates:staff?0:1,company_groups:empty?0:1,statuses:empty?[]:[{origin:'internal',status:'applied',count:internal}],stages:empty?[]:[{stage:'P0',count:internal,known_age_count:0,mean_age_days:null}],activity:empty?[]:[{day:'2026-03-08',origin:'internal',count:internal}],companies:empty?[]:[{origin:'internal',company:'Synthetic Employer',count:internal}],sources:empty?[]:[{origin:'internal',source:'KerjaOS',count:internal}],outcomes:empty?[]:[{origin:'internal',denominator:internal,interviews:0,offers:1,hires:0,rejections:0,withdrawals:0,closures:0},...(!staff?[{origin:'manual',denominator:1,interviews:1,offers:0,hires:0,rejections:0,withdrawals:0,closures:0}]:[])],observed_funnel:[]};}
 await route.fulfill({status,json:data});});await page.goto('/foundation');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('navigation',{name:'Workspace taskbar'}).getByRole('button',{name:'Analytics',exact:true}).click();return {page,context,panel:page.getByRole('region',{name:'Analytics workspace',exact:true})};}
 const a=await start('a@example.test'),b=await start('b@example.test'),hm=await start('hm@example.test');
 for(const item of [a,b,hm]){await item.panel.getByLabel('Analytics from',{exact:true}).fill('2026-01-01');await item.panel.getByLabel('Analytics until',{exact:true}).fill('2026-12-31');if(item===hm)await item.panel.getByLabel('Analytics scope',{exact:true}).selectOption('staff');await item.panel.getByRole('button',{name:'Load analytics',exact:true}).click();await expect(item.panel).toContainText('Unknown applied dates excluded');await expect(item.panel).toContainText('Unknown');}
 await expect(a.panel).toContainText('Cohort records: 3');await expect(b.panel).toContainText('Cohort records: 2');await expect(hm.panel).toContainText('Cohort records: 2');await expect(hm.panel.getByRole('table').first()).not.toContainText('manual');await expect(a.panel.getByLabel('Analytics scope',{exact:true}).getByRole('option',{name:'Assigned jobs · staff MFA',exact:true})).toHaveCount(0);
 const link=a.panel.getByRole('link',{name:'Export analytics CSV',exact:true});await expect(link).toHaveAttribute('href',/from_date=2026-01-01/);await a.panel.getByLabel('Analytics company',{exact:true}).fill('unsaved');await expect(link).not.toHaveAttribute('href',/unsaved/);
 for(const item of [a,hm])for(const theme of ['classic','luna']){await item.page.getByLabel('Desktop theme',{exact:true}).selectOption(theme);expect((await new AxeBuilder({page:item.page}).include('.foundation').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);}
 await a.page.setViewportSize({width:390,height:844});await expect.poll(()=>a.page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await a.panel.getByLabel('Analytics company',{exact:true}).fill('absent');await a.panel.getByRole('button',{name:'Load analytics',exact:true}).click();await expect(a.panel).toContainText('Cohort records: 0');await expect(a.panel).toContainText('No data in this cohort');await a.page.getByLabel('Language / Bahasa',{exact:true}).selectOption('ms');await expect(a.page.getByRole('region',{name:'Ruang analitik',exact:true})).toContainText('Rekod kohort');await a.context.close();await b.context.close();await hm.context.close();
});
