import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('owned reminders support due/snooze/complete/cancel, opt-out and truthful disabled email across themes',async({browser})=>{
 const records:any[]=[],events:any[]=[],preferences:any={a:{email_opt_in:false,revision:0},b:{email_opt_in:false,revision:0}};
 async function start(email:string){let owner='';const context=await browser.newContext(),page=await context.newPage();await page.route('**/api/v1/**',async route=>{const req=route.request(),p=new URL(req.url()).pathname;let data:any=[],status=200;
 if(p.endsWith('/auth/login')){owner=email.startsWith('a')?'a':'b';data={};}else if(p.endsWith('/me')){status=owner?200:401;data=owner?{id:owner,email,aal:'aal1',csrf_token:'fixture',memberships:[],password_recovery:false}:{detail:'Sign in required'};}
 else if(p.endsWith('/applications')||p.endsWith('/jobs'))data=[];
 else if(p.includes('/interviews/'))data=p.endsWith('/context')?{applications:[],slots:[],bookings:[],interviewers:[],email_delivery:'disabled'}:[];
 else if(p.includes('/identity/'))data=p.endsWith('/policy')?{version:'fixture',text:{en:'Synthetic',ms:'Sintetik'},real_capture_enabled:false}:[];
 else if(p.includes('/background/'))data=p.endsWith('/policy')?{checks:[]}:[];
 else if(p.includes('/discover/'))data=p.endsWith('/progress')?{enabled:false,sources:[]}:[];
 else if(p.endsWith('/reminders/context'))data={now:new Date().toISOString(),policy:{enabled:false,mode:'disabled'},preference:preferences[owner],reminders:records.filter(r=>r.owner===owner).map(r=>({...r,due:Date.parse(r.due_at)<Date.now()&&r.state==='active',delivery:'not_queued'})),worker_configured:false,sender_configured:false};
 else if(p.endsWith('/reminders/edit')){expect(req.headers()['x-csrf-token']).toBe('fixture');const b=req.postDataJSON();expect(b.recipient).toBeUndefined();expect(b.owner_id).toBeUndefined();expect(b.idempotency_key).toMatch(/^[a-f0-9-]{36}$/);if(b.action==='create'){data={...b,id:crypto.randomUUID(),owner,state:'active',revision:0};records.push(data);events.push({reminder_id:data.id,event:'created',revision:0,due_at:data.due_at});}else{const r=records.find(r=>r.id===b.id&&r.owner===owner);expect(r.revision).toBe(b.expected_revision);if(b.action==='forget')records.splice(records.indexOf(r),1);else{r.revision++;r.state=b.action==='complete'?'completed':b.action==='cancel'?'cancelled':'active';if(b.action==='snooze')r.due_at=b.due_at;events.push({reminder_id:r.id,event:b.action,revision:r.revision,due_at:r.due_at});}data={};}}
 else if(p.endsWith('/reminders/preference')){expect(req.headers()['x-csrf-token']).toBe('fixture');const b=req.postDataJSON();expect(b.expected_revision).toBe(preferences[owner].revision);preferences[owner]={email_opt_in:b.email_opt_in,revision:b.expected_revision+1};data=preferences[owner];}
 else if(p.includes('/reminders/history/'))data=events.filter(e=>e.reminder_id===p.split('/').pop());
 else if(p.endsWith('/reminders/email-preview'))data={subject:'KerjaOS reminder',body:'A personal reminder is due. No employer has been contacted.',recipient:'Your verified account email only',delivery:'Disabled by default'};
 await route.fulfill({status,json:data});});await page.goto('/foundation?view=Reminders');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();const panel=page.getByRole('region',{name:'Reminder workspace',exact:true});await panel.getByRole('button',{name:'Load reminders',exact:true}).click();return {page,panel,context};}
 const a=await start('a@example.test'),b=await start('b@example.test');await expect(a.panel).toContainText('Disabled / worker unavailable');await expect(a.panel).toContainText('No reminders yet');
 await a.panel.getByLabel('Reminder title',{exact:true}).fill('Private follow up');await a.panel.getByLabel('Reminder due time',{exact:true}).fill(new Date(Date.now()-30000).toISOString());await a.panel.getByLabel('Reminder due time',{exact:true}).press('Enter');await expect(a.panel.getByRole('heading',{name:'Private follow up',exact:true})).toBeVisible();await expect(a.panel).toContainText('Due');await b.panel.getByRole('button',{name:'Load reminders',exact:true}).click();await expect(b.panel).not.toContainText('Private follow up');
 await a.panel.getByLabel('Snooze due time',{exact:true}).fill(new Date(Date.now()+86400000).toISOString());await a.panel.getByRole('button',{name:'Snooze Private follow up',exact:true}).click();await expect(a.panel).toContainText('Upcoming');await a.panel.getByRole('button',{name:'History Private follow up',exact:true}).click();await expect(a.panel.getByRole('region',{name:'Reminder history',exact:true})).toContainText('snooze');await a.panel.getByRole('button',{name:'Complete Private follow up',exact:true}).click();await expect(a.panel).toContainText('completed');
 await a.panel.getByRole('button',{name:'Opt in to account reminder email',exact:true}).click();await expect(a.panel).toContainText('Opted in');await expect(a.panel).toContainText('Disabled / worker unavailable');await a.panel.getByRole('button',{name:'Preview reminder email',exact:true}).click();await expect(a.panel.getByRole('region',{name:'Reminder email preview',exact:true})).toContainText('No employer has been contacted');await a.panel.getByRole('button',{name:'Unsubscribe reminder email',exact:true}).click();await expect(a.panel).toContainText('Opted out');
 await a.panel.getByLabel('Reminder title',{exact:true}).fill('Cancel task');await a.panel.getByRole('button',{name:'Create reminder',exact:true}).click();await a.panel.getByRole('button',{name:'Cancel Cancel task',exact:true}).click();await expect(a.panel).toContainText('cancelled');await a.panel.getByRole('button',{name:'Forget reminder Private follow up',exact:true}).click();await expect(a.panel.getByRole('heading',{name:'Private follow up',exact:true})).toHaveCount(0);
 await a.panel.getByLabel('Reminder title',{exact:true}).fill('Unsaved draft');await a.page.getByRole('navigation',{name:'Workspace taskbar'}).getByRole('button',{name:'Tracker',exact:true}).click();await a.page.getByRole('navigation',{name:'Workspace taskbar'}).getByRole('button',{name:'Reminders',exact:true}).click();await expect(a.panel.getByLabel('Reminder title',{exact:true})).toHaveValue('Unsaved draft');
 for(const theme of ['classic','luna']){await a.page.getByLabel('Desktop theme',{exact:true}).selectOption(theme);expect((await new AxeBuilder({page:a.page}).include('.foundation').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);}
 await a.page.setViewportSize({width:390,height:844});await expect.poll(()=>a.page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await a.page.getByLabel('Language / Bahasa',{exact:true}).selectOption('ms');await expect(a.page.getByRole('region',{name:'Ruang peringatan',exact:true})).toContainText('Peringatan saya');await a.context.close();await b.context.close();
});
