import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('owned tracker links companies/resume versions and preserves internal snapshots across external edits',async({browser})=>{
 const ax=crypto.randomUUID(),ay=crypto.randomUUID(),bx=crypto.randomUUID(),companies:any[]=[],manual:any[]=[],resumes:any[]=[],links:any[]=[];
 const applications=[{id:ax,owner:'a',job_id:'X',job_title:'Internal X',stage:'P0',status:'applied',version:0},{id:ay,owner:'a',job_id:'Y',job_title:'Internal Y',stage:'P0',status:'applied',version:0},{id:bx,owner:'b',job_id:'X',job_title:'Internal X',stage:'P0',status:'applied',version:0}];
 async function attach(page:any){let owner='';await page.route('**/api/v1/**',async(route:any)=>{const req=route.request(),u=new URL(req.url()),p=u.pathname;let data:any=[];let code=200;
 if(p.endsWith('/auth/login')){owner=req.postDataJSON().email.startsWith('a')?'a':'b';data={};}
 else if(p.endsWith('/me')){code=owner?200:401;data=owner?{id:owner,email:owner+'@example.test',aal:'aal1',csrf_token:'fixture',memberships:[],password_recovery:false}:{detail:'Sign in required'};}
 else if(p.endsWith('/applications'))data=applications.filter(a=>a.owner===owner);
 else if(p.endsWith('/jobs'))data=[];
 else if(p.includes('/interviews/'))data=p.endsWith('/context')?{applications:[],slots:[],bookings:[],interviewers:[],email_delivery:'disabled'}:[];
 else if(p.includes('/identity/'))data=p.endsWith('/policy')?{version:'identity-v1',text:{en:'Synthetic',ms:'Sintetik'},real_capture_enabled:false}:[];
 else if(p.includes('/background/'))data=p.endsWith('/policy')?{checks:[]}:[];
 else if(p.includes('/discover/'))data=p.endsWith('/progress')?{enabled:false,sources:[]}:[];
 else if(p.endsWith('/tracker/companies')){if(req.method()==='POST'){const b=req.postDataJSON();expect(req.headers()['x-csrf-token']).toBe('fixture');const c={...b,id:b.id||crypto.randomUUID(),owner,revision:b.expected_revision+Number(Boolean(b.id))};if(b.id){const old=companies.find(c=>c.id===b.id&&c.owner===owner);Object.assign(old,c);}else companies.push(c);data=c;}else data=companies.filter(c=>c.owner===owner);}
 else if(p.endsWith('/tracker/resumes/upload')){data={id:crypto.randomUUID(),label:'Version one',owner,state:'ready',created_at:new Date().toISOString(),expires_at:'2027-01-01T00:00:00Z',deleted_at:null,application_copies:0};resumes.push(data);}
 else if(p.endsWith('/tracker/resumes'))data=resumes.filter(v=>v.owner===owner);
 else if(p.endsWith('/tracker/resume-links'))data=links.filter(l=>applications.some(a=>a.id===l.application_id&&a.owner===owner));
 else if(p.endsWith('/clone')){const b=req.postDataJSON();const id=p.split('/')[5];expect(applications.find(a=>a.id===b.application_id)?.owner).toBe(owner);links.push({document_id:crypto.randomUUID(),application_id:b.application_id,version_id:id,submitted_snapshot:false});resumes.find(v=>v.id===id).application_copies++;data={};}
 else if(p.endsWith('/access'))data={url:'/api/v1/tracker/resume-view?ticket=synthetic',expires_in:60};
 else if(p.endsWith('/retire')){const id=p.split('/')[5];Object.assign(resumes.find(v=>v.id===id),{label:'[removed]',expires_at:'2020-01-01T00:00:00Z'});data={access_revoked:true,object_cleanup:'pending'};}
 else if(p.endsWith('/tracker/manual')){const b=req.postDataJSON();const old=b.id?manual.find(m=>m.id===b.id&&m.owner===owner):null;expect(companies.find(c=>c.id===b.company_id)?.owner).toBe(owner);data={...b,id:b.id||crypto.randomUUID(),owner,origin:'manual',company:companies.find(c=>c.id===b.company_id).name,revision:old?old.revision+1:0};if(old)Object.assign(old,data);else manual.push(data);}
 else if(p.endsWith('/tracker/forget')){const b=req.postDataJSON();const index=manual.findIndex(m=>m.id===b.id&&m.owner===owner);if(index>=0)manual.splice(index,1);data={forgotten:true};}
 else if(p.includes('/tracker/history/'))data=[{id:'event',status:'applied',reason:'Candidate self-reported application',created_at:new Date().toISOString()}];
 else if(p.endsWith('/tracker/list')){data=[...applications.filter(a=>a.owner===owner).map(a=>({...a,origin:'internal',company:'Internal employer',title:a.job_title,applied_on:'2026-10-05',url:'',note:''})),...manual.filter(m=>m.owner===owner)];if(!u.searchParams.get('archived')||u.searchParams.get('archived')==='false')data=data.filter((r:any)=>!r.archived);const origin=u.searchParams.get('origin');if(origin&&origin!=='all')data=data.filter((r:any)=>r.origin===origin);}
 await route.fulfill({status:code,json:data});});}
 async function login(page:any,email:string){await attach(page);await page.goto('/foundation');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('navigation',{name:'Workspace navigation'}).getByRole('button',{name:'Tracker',exact:true}).click();}
 const ac=await browser.newContext(),bc=await browser.newContext(),a=await ac.newPage(),b=await bc.newPage();await login(a,'a@example.test');await login(b,'b@example.test');const panel=a.getByRole('region',{name:'Tracker workspace',exact:true}),other=b.getByRole('region',{name:'Tracker workspace',exact:true});
 await panel.getByRole('button',{name:'Load tracker',exact:true}).click();await panel.getByLabel('Company name',{exact:true}).fill('Synthetic Company');await panel.getByLabel('Company domain',{exact:true}).fill('example.test');await panel.getByLabel('Private company note',{exact:true}).fill('Private candidate note');await panel.getByRole('button',{name:'Save company',exact:true}).click();await expect(panel).toContainText('Private candidate note');
 await panel.getByLabel('Resume version label',{exact:true}).fill('Version one');await panel.getByLabel('Library PDF',{exact:true}).setInputFiles({name:'resume.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-synthetic browser fixture; API validates real PDFs separately')});await panel.getByRole('button',{name:'Upload resume version',exact:true}).click();await expect(panel.getByLabel('Library PDF',{exact:true})).toHaveValue('');await panel.getByRole('combobox',{name:'Copy resume version',exact:true}).selectOption(resumes[0].id);await panel.getByRole('combobox',{name:'Copy to application',exact:true}).selectOption(ax);await panel.getByRole('button',{name:'Create application resume copy',exact:true}).click();await expect(panel).toContainText('Application copy created');
 await panel.getByRole('combobox',{name:'Record company',exact:true}).selectOption(companies[0].id);await panel.getByLabel('External role title',{exact:true}).fill('External API role');await a.getByRole('navigation',{name:'Workspace navigation'}).getByRole('button',{name:'Discover',exact:true}).click();await a.getByRole('navigation',{name:'Workspace navigation'}).getByRole('button',{name:'Tracker',exact:true}).click();await expect(panel.getByLabel('External role title',{exact:true})).toHaveValue('External API role');
 await panel.getByLabel('External job URL',{exact:true}).fill('https://example.test/jobs/1');await panel.getByRole('combobox',{name:'Self-reported status',exact:true}).selectOption('applied');await panel.getByRole('combobox',{name:'Submitted resume version',exact:true}).selectOption(resumes[0].id);await panel.getByRole('button',{name:'Save external record',exact:true}).click();await expect(panel.getByRole('heading',{name:'External API role',exact:true})).toBeVisible();await expect(panel).toContainText('Unknown');
 await other.getByRole('button',{name:'Load tracker',exact:true}).click();await expect(other).not.toContainText('Private candidate note');await expect(other.getByRole('heading',{name:'External API role',exact:true})).toHaveCount(0);await expect(other.getByRole('heading',{name:'Internal X',exact:true})).toHaveCount(1);
 await panel.getByRole('button',{name:'Edit external record',exact:true}).click();await panel.getByRole('combobox',{name:'Self-reported status',exact:true}).selectOption('interview');await panel.getByLabel('Known applied date',{exact:true}).fill('2026-10-01');await panel.getByRole('button',{name:'Save external record',exact:true}).click();expect(applications.find(x=>x.id===ax)?.status).toBe('applied');expect(applications.find(x=>x.id===bx)?.status).toBe('applied');
 await panel.getByRole('button',{name:'Preview resume Version one',exact:true}).click();await expect(panel.getByRole('link',{name:'Private PDF · 60 seconds',exact:true})).toHaveAttribute('href','/api/v1/tracker/resume-view?ticket=synthetic');
 for(const theme of ['light','dark']){await a.getByRole('combobox',{name:'Theme',exact:true}).selectOption(theme);expect((await new AxeBuilder({page:a}).include('.foundation').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);}
 await a.setViewportSize({width:390,height:844});await expect.poll(()=>a.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await panel.getByRole('button',{name:'Remove library version Version one',exact:true}).click();await expect(panel).toContainText('Application copies retained');expect(links.length).toBe(1);
 await panel.getByRole('button',{name:'Forget external record',exact:true}).click();await expect(panel.getByRole('heading',{name:'External API role',exact:true})).toHaveCount(0);await a.getByRole('combobox',{name:'Language / Bahasa',exact:true}).selectOption('ms');await expect(a.getByRole('region',{name:'Ruang penjejak',exact:true})).toContainText('Syarikat peribadi');await ac.close();await bc.close();
});
